//! Near-anchor band gate for `Decimal128` (fd-aqs.6).
//!
//! The 2026-06-09 review found the shared Extended kernel losing
//! relative accuracy near the additive anchors 0 and 1: formulas
//! handing `1 ± tiny` (or an absorbed `x²` correction) to the
//! 50-significant-digit working representation turned the kernel's
//! ~1e-49 *relative* error model *absolute*, mis-rounding `ln`,
//! `log10`, and `log2` just below 1 (up to ~4e7 ULP at Decimal128),
//! `atanh` and `asinh` in the small-argument band (up to ~3e8 ULP),
//! `asin` and `acos` near ±1, and `pow` through `y · ln x`. The Arb
//! corpus decades stop short of these bands and the astro-float
//! suites assert only the weaker faithful contract, so the class was
//! invisible to every prior layer; this gate closes the class, not
//! the instances.
//!
//! The corpus (`tests/vectors/transcend/anchor_bands/`) is committed
//! data generated by `tools/gen_anchor_band_vectors.py`: mpmath at
//! 160 dps under a 1e-90 ULP boundary-margin guard, with libmpdec
//! cross-confirmation for `ln`/`log10`/`pow` at `NearestEven`.
//! The ADR-0051 residual seam decides the grid-hugging cases, so
//! they carry directed-mode lines too; only corrections below the
//! generator's oracle floor stay nearest-modes-only. The corpus
//! also covers the small-argument trigonometric, hyperbolic, and
//! exponential families the seam serves.
//!
//! The per-(function, mode) counts are pinned exactly, per the
//! repository's regression-guard discipline: a floor would let a
//! silent corpus trim hide behind the total.

#![cfg(all(
    feature = "exp-log",
    feature = "trig",
    feature = "hyperbolic",
    feature = "pow"
))]

use core::cmp::Ordering;
use std::collections::BTreeMap;

use ferrodec::{Decimal128, RoundingMode};
use ferrodec_test_support::frozen;

const PREC: u32 = 34;

/// Exact expected count per `(func, mode)` bucket at `PREC`.
/// Regenerating the corpus updates these pins in the same commit.
const EXPECTED: &[(&str, &str, usize)] = &[
    ("acos", "NearestEven", 11),
    ("acos", "NearestAway", 11),
    ("acos", "TowardZero", 11),
    ("acos", "TowardPositive", 11),
    ("acos", "TowardNegative", 11),
    ("asin", "NearestEven", 8),
    ("asin", "NearestAway", 8),
    ("asin", "TowardZero", 8),
    ("asin", "TowardPositive", 8),
    ("asin", "TowardNegative", 8),
    ("asinh", "NearestEven", 16),
    ("asinh", "NearestAway", 16),
    ("asinh", "TowardZero", 16),
    ("asinh", "TowardPositive", 16),
    ("asinh", "TowardNegative", 16),
    ("atan", "NearestEven", 16),
    ("atan", "NearestAway", 16),
    ("atan", "TowardZero", 16),
    ("atan", "TowardPositive", 16),
    ("atan", "TowardNegative", 16),
    ("atanh", "NearestEven", 16),
    ("atanh", "NearestAway", 16),
    ("atanh", "TowardZero", 16),
    ("atanh", "TowardPositive", 16),
    ("atanh", "TowardNegative", 16),
    ("cos", "NearestEven", 4),
    ("cos", "NearestAway", 4),
    ("cos", "TowardZero", 4),
    ("cos", "TowardPositive", 4),
    ("cos", "TowardNegative", 4),
    ("cosh", "NearestEven", 4),
    ("cosh", "NearestAway", 4),
    ("cosh", "TowardZero", 4),
    ("cosh", "TowardPositive", 4),
    ("cosh", "TowardNegative", 4),
    ("exp", "NearestEven", 4),
    ("exp", "NearestAway", 4),
    ("exp", "TowardZero", 4),
    ("exp", "TowardPositive", 4),
    ("exp", "TowardNegative", 4),
    ("exp2", "NearestEven", 4),
    ("exp2", "NearestAway", 4),
    ("exp2", "TowardZero", 4),
    ("exp2", "TowardPositive", 4),
    ("exp2", "TowardNegative", 4),
    ("ln", "NearestEven", 12),
    ("ln", "NearestAway", 12),
    ("ln", "TowardZero", 12),
    ("ln", "TowardPositive", 12),
    ("ln", "TowardNegative", 12),
    ("log10", "NearestEven", 12),
    ("log10", "NearestAway", 12),
    ("log10", "TowardZero", 12),
    ("log10", "TowardPositive", 12),
    ("log10", "TowardNegative", 12),
    ("log2", "NearestEven", 12),
    ("log2", "NearestAway", 12),
    ("log2", "TowardZero", 12),
    ("log2", "TowardPositive", 12),
    ("log2", "TowardNegative", 12),
    ("pow", "NearestEven", 3),
    ("pow", "NearestAway", 3),
    ("pow", "TowardZero", 3),
    ("pow", "TowardPositive", 3),
    ("pow", "TowardNegative", 3),
    ("sin", "NearestEven", 16),
    ("sin", "NearestAway", 16),
    ("sin", "TowardZero", 16),
    ("sin", "TowardPositive", 16),
    ("sin", "TowardNegative", 16),
    ("sinh", "NearestEven", 16),
    ("sinh", "NearestAway", 16),
    ("sinh", "TowardZero", 16),
    ("sinh", "TowardPositive", 16),
    ("sinh", "TowardNegative", 16),
    ("tan", "NearestEven", 16),
    ("tan", "NearestAway", 16),
    ("tan", "TowardZero", 16),
    ("tan", "TowardPositive", 16),
    ("tan", "TowardNegative", 16),
    ("tanh", "NearestEven", 16),
    ("tanh", "NearestAway", 16),
    ("tanh", "TowardZero", 16),
    ("tanh", "TowardPositive", 16),
    ("tanh", "TowardNegative", 16),
];

fn parse(s: &str) -> Decimal128 {
    Decimal128::parse_str(s, RoundingMode::NearestEven)
        .unwrap_or_else(|_| panic!("anchor-band token parses: {s:?}"))
        .0
}

fn mode(s: &str) -> RoundingMode {
    match s {
        "NearestEven" => RoundingMode::NearestEven,
        "NearestAway" => RoundingMode::NearestAway,
        "TowardZero" => RoundingMode::TowardZero,
        "TowardPositive" => RoundingMode::TowardPositive,
        "TowardNegative" => RoundingMode::TowardNegative,
        other => panic!("anchor-band corpus has an unknown rounding mode {other:?}"),
    }
}

fn kernel(v: &frozen::FrozenVec, rm: RoundingMode) -> Decimal128 {
    let x = parse(&v.input);
    match v.func.as_str() {
        "pow" => x.pow(parse(v.input2.as_deref().expect("pow input2")), rm).0,
        "ln" => x.ln(rm).0,
        "log10" => x.log10(rm).0,
        "log2" => x.log2(rm).0,
        "atanh" => x.atanh(rm).0,
        "asinh" => x.asinh(rm).0,
        "asin" => x.asin(rm).0,
        "acos" => x.acos(rm).0,
        "sin" => x.sin(rm).0,
        "cos" => x.cos(rm).0,
        "tan" => x.tan(rm).0,
        "atan" => x.atan(rm).0,
        "sinh" => x.sinh(rm).0,
        "cosh" => x.cosh(rm).0,
        "tanh" => x.tanh(rm).0,
        "exp" => x.exp(rm).0,
        "exp2" => x.exp2(rm).0,
        other => panic!("anchor-band corpus has no kernel mapping for {other:?}"),
    }
}

#[test]
fn anchor_band_vectors_correctly_rounded() {
    let vectors = frozen::load_anchor_bands(PREC);
    let mut by_bucket: BTreeMap<(String, String), usize> = BTreeMap::new();
    for v in &vectors {
        let rm = mode(&v.mode);
        let cr = parse(&v.output);
        let got = kernel(v, rm);
        assert_eq!(
            got.partial_cmp(cr).0,
            Some(Ordering::Equal),
            "anchor-band contract violated [{}]: {}({}{}) -> ferrodec {} | \
             correctly rounded {}",
            v.mode,
            v.func,
            v.input,
            v.input2
                .as_deref()
                .map(|y| format!(", {y}"))
                .unwrap_or_default(),
            got,
            cr
        );
        *by_bucket
            .entry((v.func.clone(), v.mode.clone()))
            .or_insert(0) += 1;
    }
    // Exact per-bucket pins: a regenerated corpus that drops a
    // function or a mode fails here rather than passing silently.
    for (func, md, want) in EXPECTED {
        let got = by_bucket
            .get(&((*func).to_string(), (*md).to_string()))
            .copied()
            .unwrap_or(0);
        assert_eq!(
            got, *want,
            "anchor-band bucket {func}/{md}: {got} vectors, pinned {want}"
        );
    }
    let pinned: usize = EXPECTED.iter().map(|(_, _, n)| n).sum();
    assert_eq!(
        vectors.len(),
        pinned,
        "anchor-band corpus carries unpinned vectors at p{PREC}"
    );
}
