//! Boundary distance measurement on 50 digit `Extended` intermediates.
//!
//! A `Decimal128` result misrounds only when the infinitely precise
//! value sits closer to a rounding boundary of the 34 digit grid than
//! the kernel's own error. The campaign filter therefore measures, for
//! each kernel intermediate, the exact distance to the two boundary
//! families:
//!
//! - the **grid point** (a representable value; the directed mode
//!   boundary), and
//! - the **half ULP midpoint** (the nearest mode tie).
//!
//! Distances are exact integers. Normalize the coefficient to exactly
//! [`EXT_PRECISION`] digits; with target precision `p` the drop width
//! is `w = EXT_PRECISION - p`, the tail is `T = coef50 mod 10^w`, and
//! in units of `10^-w / 2` ULP the distances are `2·min(T, 10^w - T)`
//! (grid) and `|2·T - 10^w|` (midpoint). This is the same normalization
//! `tools/gen_transcend_vectors.py::{directed_margin, tie_margin}`
//! performs on exact `Fraction`s; the committed lockstep table
//! (`tests/vectors/margin_lockstep.txt`, generated by
//! `tools/gen_margin_lockstep.py`) pins the two implementations to
//! each other, and the generator itself asserts the integer
//! formulation against the `gtv` functions at generation time. The
//! filter and the corpus generator's margin definition are provably
//! the same function, which is what the S1 soundness argument leans
//! on (ADR-0059).
//!
//! Scope: distances are measured on the **normal range** grid (drop
//! width `EXT_PRECISION - p`). Results in a format's subnormal band
//! have a wider effective drop; the sampler passes that width through
//! [`boundary_distances_at_width`] explicitly. This module is the
//! campaign filter, not the runtime escalation predicate (that is
//! mechanism slice M2, which additionally handles `q_preferred` and
//! the exact subnormal seam inside the kernel).

use ferrodec_multiword::U256;
use ferrodec_transcend::extended::Extended;

/// The kernel's working precision in decimal digits. `ferrodec-transcend`
/// keeps this `pub(crate)`; the value here is pinned by the
/// `ext_precision_pin` test against a live kernel intermediate rather
/// than imported, so drift fails a test instead of compiling wrong.
pub const EXT_PRECISION: u32 = 50;

/// Exact boundary distances of one intermediate, in units of
/// `10^-w / 2` ULP of the target grid (so both families are integers:
/// an exact grid hit is `grid_x2 == 0`, an exact tie is `tie_x2 == 0`,
/// and the maximum of either family is `10^w`).
#[derive(Clone, Copy, Debug)]
pub struct BoundaryDistances {
    /// Drop width: digits of the 50 digit coefficient below the target
    /// grid.
    pub w: u32,
    /// `2 · min(T, 10^w - T)`: doubled distance to the nearest grid
    /// point.
    pub grid_x2: U256,
    /// `|2·T - 10^w|`: doubled distance to the half ULP midpoint.
    pub tie_x2: U256,
}

/// Which boundary families a threshold test matched.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Within {
    pub grid: bool,
    pub tie: bool,
}

impl BoundaryDistances {
    /// True per family when the distance is strictly below
    /// `num · 10^-neg_pow10` ULP. Exact integer comparison:
    /// `dist_x2 · 10^neg_pow10 < 2 · num · 10^w`.
    ///
    /// # Panics
    ///
    /// When the bounds that keep the cross multiplication inside
    /// `U256` are violated: `num <= 10^12` and
    /// `w + neg_pow10 <= 70`.
    #[must_use]
    pub fn within_ulp(&self, num: u128, neg_pow10: u32) -> Within {
        assert!(num <= 10u128.pow(12), "threshold numerator too large");
        assert!(
            self.w + neg_pow10 <= 70,
            "width {} + threshold exponent {neg_pow10} exceeds the U256 envelope",
            self.w
        );
        let rhs = U256::from_u128(2 * num).mul_pow10(self.w);
        let within = |dist_x2: U256| dist_x2.mul_pow10(neg_pow10).cmp(rhs).is_lt();
        Within {
            grid: within(self.grid_x2),
            tie: within(self.tie_x2),
        }
    }
}

/// Boundary distances of `x` against the `prec` digit normal range
/// grid (`w = EXT_PRECISION - prec`). `None` for a zero coefficient
/// (zero is an anchor family case the campaign never filters on) or a
/// coefficient wider than [`EXT_PRECISION`] digits (an intermediate
/// contract violation the caller must treat as a finding, not skip).
#[must_use]
pub fn boundary_distances(x: Extended, prec: u32) -> Option<BoundaryDistances> {
    assert!((1..EXT_PRECISION).contains(&prec), "precision out of range");
    boundary_distances_at_width(x, EXT_PRECISION - prec)
}

/// Boundary distances at an explicit drop width `w` (the subnormal
/// band form: the sampler widens `w` by the exponent shortfall).
/// The margin is decade invariant, so `x.exp` and `x.sign` do not
/// enter; only the coefficient does.
#[must_use]
pub fn boundary_distances_at_width(x: Extended, w: u32) -> Option<BoundaryDistances> {
    assert!(
        (1..=60).contains(&w),
        "drop width out of the supported range"
    );
    if x.coef.is_zero() {
        return None;
    }
    let dig = x.coef.decimal_digit_count();
    if dig > EXT_PRECISION {
        return None;
    }
    let coef50 = x.coef.mul_pow10(EXT_PRECISION - dig);

    // T = coef50 mod 10^w via a div_rem10 walk (w <= 60 steps).
    let mut q = coef50;
    for _ in 0..w {
        q = q.div_rem10().0;
    }
    let t = coef50.sub(q.mul_pow10(w));

    let pow_w = U256::from_u128(1).mul_pow10(w);
    let hi = pow_w.sub(t);
    let grid_min = if t.cmp(hi).is_lt() { t } else { hi };
    let two_t = t.add(t);
    let tie_x2 = if two_t.cmp(pow_w).is_lt() {
        pow_w.sub(two_t)
    } else {
        two_t.sub(pow_w)
    };
    Some(BoundaryDistances {
        w,
        grid_x2: grid_min.add(grid_min),
        tie_x2,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::u256_from_decimal;

    fn ext(coef: &str, exp: i32) -> Extended {
        Extended {
            coef: u256_from_decimal(coef).expect("test coefficient"),
            exp,
            sign: false,
        }
    }

    fn pow10(w: u32) -> U256 {
        U256::from_u128(1).mul_pow10(w)
    }

    #[test]
    fn exact_grid_point() {
        // 34 significant digits then 16 zeros: T = 0 at p = 34.
        let x = ext(
            &format!("{}{}", "1234567890123456789012345678901234", "0".repeat(16)),
            -10,
        );
        let d = boundary_distances(x, 34).unwrap();
        assert_eq!(d.w, 16);
        assert!(d.grid_x2.is_zero());
        assert_eq!(d.tie_x2.cmp(pow10(16)), core::cmp::Ordering::Equal);
        let w = d.within_ulp(1, 6);
        assert!(w.grid && !w.tie);
    }

    #[test]
    fn exact_tie() {
        // T = 5·10^15 at p = 34: the half ULP midpoint exactly.
        let x = ext(
            &format!(
                "{}5{}",
                "1234567890123456789012345678901234",
                "0".repeat(15)
            ),
            3,
        );
        let d = boundary_distances(x, 34).unwrap();
        assert!(d.tie_x2.is_zero());
        assert_eq!(d.grid_x2.cmp(pow10(16)), core::cmp::Ordering::Equal);
        let w = d.within_ulp(1, 6);
        assert!(w.tie && !w.grid);
    }

    #[test]
    fn one_unit_above_grid() {
        // T = 1: grid_x2 = 2, tie_x2 = 10^16 - 2.
        let x = ext(
            &format!(
                "{}{}1",
                "1234567890123456789012345678901234",
                "0".repeat(15)
            ),
            0,
        );
        let d = boundary_distances(x, 34).unwrap();
        assert_eq!(
            d.grid_x2.cmp(U256::from_u128(2)),
            core::cmp::Ordering::Equal
        );
        assert_eq!(
            d.tie_x2.cmp(pow10(16).sub(U256::from_u128(2))),
            core::cmp::Ordering::Equal
        );
    }

    #[test]
    fn decade_and_sign_invariance() {
        let a = ext("98765432109876543210987654321098765432109876543219", -300);
        let mut b = a;
        b.exp = 4000;
        b.sign = true;
        let (da, db) = (
            boundary_distances(a, 16).unwrap(),
            boundary_distances(b, 16).unwrap(),
        );
        assert_eq!(da.grid_x2.cmp(db.grid_x2), core::cmp::Ordering::Equal);
        assert_eq!(da.tie_x2.cmp(db.tie_x2), core::cmp::Ordering::Equal);
    }

    #[test]
    fn short_coefficient_normalizes() {
        // A 1 digit coefficient is 7 followed by 49 zeros at width 50:
        // T = 0 on every grid.
        let x = ext("7", 0);
        for p in [7u32, 16, 34] {
            let d = boundary_distances(x, p).unwrap();
            assert!(d.grid_x2.is_zero(), "p={p}");
        }
    }

    #[test]
    fn wide_tail_beyond_u128() {
        // p = 7 drops w = 43 digits; the tail exceeds u128 range.
        // coef50 = 10^49 + (10^43 - 1): T = 10^43 - 1, so grid_x2 = 2.
        let coef = format!("1{}{}", "0".repeat(6), "9".repeat(43));
        let d = boundary_distances(ext(&coef, 0), 7).unwrap();
        assert_eq!(d.w, 43);
        assert_eq!(
            d.grid_x2.cmp(U256::from_u128(2)),
            core::cmp::Ordering::Equal
        );
    }

    #[test]
    fn zero_and_overwide_are_none() {
        assert!(boundary_distances(
            Extended {
                coef: U256::ZERO,
                exp: 0,
                sign: false
            },
            34
        )
        .is_none());
        let overwide = ext(&"9".repeat(51), 0);
        assert!(boundary_distances(overwide, 34).is_none());
    }

    /// Pins [`EXT_PRECISION`] against a live kernel intermediate: the
    /// crate hardcodes 50 because `ferrodec-transcend` keeps the
    /// constant private; if the kernel ever widens, this fails before
    /// any campaign lies.
    #[test]
    fn ext_precision_pin() {
        let e = ferrodec_transcend::exp::exp_extended(ferrodec_transcend::consts::pi_ext());
        let dig = e.coef.decimal_digit_count();
        assert!(
            dig <= EXT_PRECISION,
            "kernel intermediate carries {dig} digits"
        );
        assert!(
            dig >= EXT_PRECISION - 1,
            "kernel intermediate unexpectedly narrow: {dig}"
        );
    }
}
