//! High-precision mathematical constants.
//!
//! Each constant is held as a 36-digit decimal literal — two extra
//! digits beyond the 34-digit Decimal128 precision so the parsed value
//! is correctly rounded for any rounding mode.
//!
//! Each call parses the string fresh. That's measurably cheap (a
//! single fixed-size scan through ~40 bytes) and avoids the
//! once-cell / static-init complexity that would otherwise leak `std`
//! into a `no_std` crate. Callers that need many uses of `pi()` or
//! `ln10()` should cache the result in a local.

use crate::decimal::Decimal128;
use crate::math::extended::Extended;
use crate::status::RoundingMode;

const PI_STR: &str = "3.14159265358979323846264338327950288";
const E_STR: &str = "2.71828182845904523536028747135266250";
const LN2_STR: &str = "0.693147180559945309417232121458176568";
const LN10_STR: &str = "2.30258509299404568401799145468436421";

// Extended-precision constants — 55 decimal digits, comfortably above
// EXT_PRECISION = 50. Generated by `tools/gen_argred.py`'s mpmath
// helpers. Used by the faithfully-rounded transcendental kernels.
const PI_EXT_STR: &str = "3.141592653589793238462643383279502884197169399375105821";
const E_EXT_STR: &str = "2.718281828459045235360287471352662497757247093699959575";
const LN2_EXT_STR: &str = "0.6931471805599453094172321214581765680755001343602552541";
const LN10_EXT_STR: &str = "2.302585092994045684017991454684364207601101488628772976";
const INV_LN10_EXT_STR: &str =
    "0.4342944819032518276511289189166050822943970058036665661";

/// `π` to 35 significant digits, rounded to Decimal128 precision.
#[must_use]
pub fn pi() -> Decimal128 {
    parse_const(PI_STR)
}

/// Euler's number `e` to 35 significant digits.
#[must_use]
pub fn e() -> Decimal128 {
    parse_const(E_STR)
}

/// `ln(2)` to 35 significant digits.
#[must_use]
pub fn ln2() -> Decimal128 {
    parse_const(LN2_STR)
}

/// `ln(10)` to 35 significant digits.
#[must_use]
pub fn ln10() -> Decimal128 {
    parse_const(LN10_STR)
}

// Extended-precision accessors --------------------------------------------

/// `π` at extended (≥ 50-digit) working precision.
#[must_use]
pub(crate) fn pi_ext() -> Extended {
    Extended::parse_str(PI_EXT_STR)
}

/// Euler's number `e` at extended precision.
#[must_use]
#[allow(dead_code)] // used by upcoming exp/pow migrations
pub(crate) fn e_ext() -> Extended {
    Extended::parse_str(E_EXT_STR)
}

/// `ln(2)` at extended precision.
#[must_use]
#[allow(dead_code)]
pub(crate) fn ln2_ext() -> Extended {
    Extended::parse_str(LN2_EXT_STR)
}

/// `ln(10)` at extended precision.
#[must_use]
pub(crate) fn ln10_ext() -> Extended {
    Extended::parse_str(LN10_EXT_STR)
}

/// `1/ln(10)` at extended precision. Used in place of `Extended` /
/// `Extended` division when reducing `x = k · ln(10) + r` for `exp`.
#[must_use]
pub(crate) fn inv_ln10_ext() -> Extended {
    Extended::parse_str(INV_LN10_EXT_STR)
}

/// Shared parse helper. The constants are hand-curated, so a parse
/// error is a programmer mistake, not a runtime condition — we
/// `expect` here.
#[inline]
fn parse_const(s: &str) -> Decimal128 {
    Decimal128::parse_str(s, RoundingMode::NearestEven)
        .expect("ferrodec math const literal must parse")
        .0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pi_is_about_three_point_one_four() {
        let p = pi();
        // 3.14 < pi < 3.15
        let three_fourteen = Decimal128::parse_str("3.14", RoundingMode::default())
            .unwrap()
            .0;
        let three_fifteen = Decimal128::parse_str("3.15", RoundingMode::default())
            .unwrap()
            .0;
        assert_eq!(
            p.partial_cmp(three_fourteen).0,
            Some(core::cmp::Ordering::Greater)
        );
        assert_eq!(
            p.partial_cmp(three_fifteen).0,
            Some(core::cmp::Ordering::Less)
        );
    }

    #[test]
    fn e_is_about_two_point_seven_one_eight() {
        let v = e();
        let two_seven = Decimal128::parse_str("2.71", RoundingMode::default())
            .unwrap()
            .0;
        let two_eight = Decimal128::parse_str("2.72", RoundingMode::default())
            .unwrap()
            .0;
        assert_eq!(
            v.partial_cmp(two_seven).0,
            Some(core::cmp::Ordering::Greater)
        );
        assert_eq!(v.partial_cmp(two_eight).0, Some(core::cmp::Ordering::Less));
    }

    #[test]
    fn ln_constants_are_positive() {
        assert!(!ln2().is_sign_negative());
        assert!(!ln10().is_sign_negative());
    }

    #[test]
    fn parse_doesnt_panic() {
        // Touch all four to confirm none of the literals regress.
        let _ = pi();
        let _ = e();
        let _ = ln2();
        let _ = ln10();
    }
}
