//! High-precision mathematical constants.
//!
//! Each constant is held as a 36-digit decimal literal — two extra
//! digits beyond the 34-digit Decimal128 precision so the parsed value
//! is correctly rounded for any rounding mode.
//!
//! Each call parses the string fresh. That's measurably cheap (a
//! single fixed-size scan through ~40 bytes) and avoids the
//! once-cell / static-init complexity that would otherwise leak `std`
//! into a `no_std` crate. Callers that need many uses of `pi()` or
//! `ln10()` should cache the result in a local.

// Some accessors are kernel-specific (`ln10_ext` is only called from
// exp / ln; `pi_ext` only from inverse_trig). Whether each is "used"
// depends on which sub-feature(s) of `transcendentals` are enabled, so
// we accept the dead-code analysis at the file level rather than
// littering each function with #[cfg].
#![allow(dead_code)]

use crate::decimal::Decimal128;
use crate::math::extended::Extended;
use crate::status::RoundingMode;

const PI_STR: &str = "3.14159265358979323846264338327950288";
const E_STR: &str = "2.71828182845904523536028747135266250";
const LN2_STR: &str = "0.693147180559945309417232121458176568";
const LN10_STR: &str = "2.30258509299404568401799145468436421";

// Extended-precision constants — 55 decimal digits, comfortably above
// EXT_PRECISION = 50. Generated by `tools/gen_argred.py`'s mpmath
// helpers. Used by the faithfully-rounded transcendental kernels.
const PI_EXT_STR: &str = "3.141592653589793238462643383279502884197169399375105821";
const E_EXT_STR: &str = "2.718281828459045235360287471352662497757247093699959575";
const LN2_EXT_STR: &str = "0.6931471805599453094172321214581765680755001343602552541";
const LN10_EXT_STR: &str = "2.302585092994045684017991454684364207601101488628772976";
const INV_LN10_EXT_STR: &str = "0.4342944819032518276511289189166050822943970058036665661";
const INV_LN2_EXT_STR: &str = "1.442695040888963407359924681001892137426645954152985934";
// π/4, π/2, and tan(π/8) at extended precision. Used by atan's
// argument reduction.
const PI_OVER_TWO_EXT_STR: &str = "1.570796326794896619231321691639751442098584699687552910";
const PI_OVER_FOUR_EXT_STR: &str = "0.7853981633974483096156608458198757210492923498437764552";
const TAN_PI_OVER_EIGHT_EXT_STR: &str = "0.4142135623730950488016887242096980785696718753769480732";

/// `π` to 35 significant digits, rounded to Decimal128 precision.
#[must_use]
pub fn pi() -> Decimal128 {
    parse_const(PI_STR)
}

/// Euler's number `e` to 35 significant digits.
#[must_use]
pub fn e() -> Decimal128 {
    parse_const(E_STR)
}

/// `ln(2)` to 35 significant digits.
#[must_use]
pub fn ln2() -> Decimal128 {
    parse_const(LN2_STR)
}

/// `ln(10)` to 35 significant digits.
#[must_use]
pub fn ln10() -> Decimal128 {
    parse_const(LN10_STR)
}

// Extended-precision accessors --------------------------------------------

/// `π` at extended (≥ 50-digit) working precision.
#[must_use]
pub(crate) fn pi_ext() -> Extended {
    Extended::parse_str(PI_EXT_STR)
}

/// Euler's number `e` at extended precision.
#[must_use]
#[allow(dead_code)] // used by upcoming exp/pow migrations
pub(crate) fn e_ext() -> Extended {
    Extended::parse_str(E_EXT_STR)
}

/// `ln(2)` at extended precision.
#[must_use]
#[allow(dead_code)]
pub(crate) fn ln2_ext() -> Extended {
    Extended::parse_str(LN2_EXT_STR)
}

/// `ln(10)` at extended precision.
#[must_use]
pub(crate) fn ln10_ext() -> Extended {
    Extended::parse_str(LN10_EXT_STR)
}

/// `1/ln(10)` at extended precision. Used in place of `Extended` /
/// `Extended` division when reducing `x = k · ln(10) + r` for `exp`.
#[must_use]
pub(crate) fn inv_ln10_ext() -> Extended {
    Extended::parse_str(INV_LN10_EXT_STR)
}

/// `1/ln(2)` at extended precision. Used by `log2(x) = ln(x) · 1/ln(2)`.
#[must_use]
pub(crate) fn inv_ln2_ext() -> Extended {
    Extended::parse_str(INV_LN2_EXT_STR)
}

/// `π/2` at extended precision. Used by atan / asin / acos /
/// atan2 quadrant adjustments.
#[must_use]
pub(crate) fn pi_over_two_ext() -> Extended {
    Extended::parse_str(PI_OVER_TWO_EXT_STR)
}

/// `π/4` at extended precision.
#[must_use]
pub(crate) fn pi_over_four_ext() -> Extended {
    Extended::parse_str(PI_OVER_FOUR_EXT_STR)
}

/// `tan(π/8)` at extended precision — the threshold for atan's
/// inner argument reduction.
#[must_use]
pub(crate) fn tan_pi_over_eight_ext() -> Extended {
    Extended::parse_str(TAN_PI_OVER_EIGHT_EXT_STR)
}

/// Shared parse helper. The constants are hand-curated, so a parse
/// error is a programmer mistake, not a runtime condition — we
/// `expect` here.
#[inline]
fn parse_const(s: &str) -> Decimal128 {
    Decimal128::parse_str(s, RoundingMode::NearestEven)
        .expect("ferrodec math const literal must parse")
        .0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pi_is_about_three_point_one_four() {
        let p = pi();
        // 3.14 < pi < 3.15
        let three_fourteen = Decimal128::parse_str("3.14", RoundingMode::default())
            .unwrap()
            .0;
        let three_fifteen = Decimal128::parse_str("3.15", RoundingMode::default())
            .unwrap()
            .0;
        assert_eq!(
            p.partial_cmp(three_fourteen).0,
            Some(core::cmp::Ordering::Greater)
        );
        assert_eq!(
            p.partial_cmp(three_fifteen).0,
            Some(core::cmp::Ordering::Less)
        );
    }

    #[test]
    fn e_is_about_two_point_seven_one_eight() {
        let v = e();
        let two_seven = Decimal128::parse_str("2.71", RoundingMode::default())
            .unwrap()
            .0;
        let two_eight = Decimal128::parse_str("2.72", RoundingMode::default())
            .unwrap()
            .0;
        assert_eq!(
            v.partial_cmp(two_seven).0,
            Some(core::cmp::Ordering::Greater)
        );
        assert_eq!(v.partial_cmp(two_eight).0, Some(core::cmp::Ordering::Less));
    }

    #[test]
    fn ln_constants_are_positive() {
        assert!(!ln2().is_sign_negative());
        assert!(!ln10().is_sign_negative());
    }

    #[test]
    fn parse_doesnt_panic() {
        // Touch all four to confirm none of the literals regress.
        let _ = pi();
        let _ = e();
        let _ = ln2();
        let _ = ln10();
    }

    // ------------------------------------------------------------------
    // Extended-precision constants oracle
    //
    // The nine `*_EXT_STR` literals above were hand-curated via mpmath
    // (see `tools/gen_argred.py`). A single transposed digit in any of
    // them would silently degrade every transcendental kernel that
    // consumes it (most visibly `INV_LN10_EXT_STR` for `log10`,
    // `LN2_EXT_STR` for `log2`, `PI_OVER_TWO_EXT_STR` for atan's
    // argument reduction).
    //
    // The 2026-05-10 six-agent review (M1) flagged the absence of an
    // independent oracle for these literals: the only test was
    // `pi_is_about_three_point_one_four`, which checks π between 3.14
    // and 3.15 — wide enough to admit any digit-transposition past
    // the third decimal.
    //
    // Slice E.3 closes the gap by re-deriving each constant via
    // `astro-float` at 220-bit working precision (~66 decimal digits)
    // and asserting agreement to ≥ 50 digits. The 50-digit envelope
    // matches `EXT_PRECISION`; a literal that drifts past 50 digits
    // would no longer round correctly through `Extended::parse_str`
    // and the assertion fires immediately.

    use astro_float::{BigFloat, Consts, RoundingMode as AfRm};

    /// Working precision for the astro-float reference computations.
    /// 220 bits ≈ 66 decimal digits — well above the 50-digit
    /// agreement target so the comparison's last bits are clean.
    const ORACLE_P: usize = 220;

    fn parse_bf(s: &str, cc: &mut Consts) -> BigFloat {
        BigFloat::parse(s, astro_float::Radix::Dec, ORACLE_P, AfRm::None, cc)
    }

    /// Assert `|our - reference| < 10^{-50}`. The bound is chosen so
    /// the agreement covers the full `EXT_PRECISION = 50` working
    /// envelope; a constant that drifts past that bound is no longer
    /// a faithful 50-digit literal.
    fn assert_ext_str_matches(label: &str, our_str: &str, reference: &BigFloat, cc: &mut Consts) {
        let ours = parse_bf(our_str, cc);
        let diff = ours.sub(reference, ORACLE_P, AfRm::None).abs();
        let tolerance = parse_bf("1e-50", cc);
        assert!(
            matches!(
                diff.partial_cmp(&tolerance),
                Some(core::cmp::Ordering::Less)
            ),
            "{label}: {our_str} differs from astro-float reference by ≥ 10⁻⁵⁰"
        );
    }

    #[test]
    fn extended_constants_match_astro_float_to_50_digits() {
        let mut cc = Consts::new().expect("init consts");

        // π
        let pi_ref = cc.pi(ORACLE_P, AfRm::None);
        assert_ext_str_matches("PI_EXT_STR", PI_EXT_STR, &pi_ref, &mut cc);

        // e = exp(1)
        let one = parse_bf("1", &mut cc);
        let e_ref = one.exp(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("E_EXT_STR", E_EXT_STR, &e_ref, &mut cc);

        // ln(2)
        let two = parse_bf("2", &mut cc);
        let ln2_ref = two.ln(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("LN2_EXT_STR", LN2_EXT_STR, &ln2_ref, &mut cc);

        // ln(10)
        let ten = parse_bf("10", &mut cc);
        let ln10_ref = ten.ln(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("LN10_EXT_STR", LN10_EXT_STR, &ln10_ref, &mut cc);

        // 1 / ln(10)
        let inv_ln10_ref = ln10_ref.reciprocal(ORACLE_P, AfRm::None);
        assert_ext_str_matches("INV_LN10_EXT_STR", INV_LN10_EXT_STR, &inv_ln10_ref, &mut cc);

        // 1 / ln(2)
        let inv_ln2_ref = ln2_ref.reciprocal(ORACLE_P, AfRm::None);
        assert_ext_str_matches("INV_LN2_EXT_STR", INV_LN2_EXT_STR, &inv_ln2_ref, &mut cc);

        // π / 2
        let pi_over_two_ref = pi_ref.div(&two, ORACLE_P, AfRm::None);
        assert_ext_str_matches(
            "PI_OVER_TWO_EXT_STR",
            PI_OVER_TWO_EXT_STR,
            &pi_over_two_ref,
            &mut cc,
        );

        // π / 4
        let four = parse_bf("4", &mut cc);
        let pi_over_four_ref = pi_ref.div(&four, ORACLE_P, AfRm::None);
        assert_ext_str_matches(
            "PI_OVER_FOUR_EXT_STR",
            PI_OVER_FOUR_EXT_STR,
            &pi_over_four_ref,
            &mut cc,
        );

        // tan(π / 8)
        let eight = parse_bf("8", &mut cc);
        let pi_over_eight = pi_ref.div(&eight, ORACLE_P, AfRm::None);
        let tan_pi_eight_ref = pi_over_eight.tan(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches(
            "TAN_PI_OVER_EIGHT_EXT_STR",
            TAN_PI_OVER_EIGHT_EXT_STR,
            &tan_pi_eight_ref,
            &mut cc,
        );
    }
}
