# Generate the oracle digit strings pinned by the runtime constant
# generators in ferrodec-multiword/src/bigconst.rs, mirroring
# tools/gen_ext2_consts.py's mpmath usage for the stored rung 1 and rung 2
# constants.
#
# Each generator returns the first `n` significant decimal digits of its
# constant as an integer: floor(c * 10^(n - 1 - E)) with E = floor(log10 c).
# This script prints that integer for every pinned depth, in a shape ready
# to paste into the `#[cfg(test)]` pin tables.
#
# Run (pure Rust ethos does not reach the oracle side; mpmath is the house
# arbitrary precision oracle):
#
#   nix-shell -p "python3.withPackages(ps: [ps.mpmath])" \
#     --run "python3 tools/gen_bigconst_oracle.py"
import sys

sys.set_int_max_str_digits(100000)

from mpmath import mp, mpf, pi, e, log, sqrt

DEPTHS = [50, 120, 220, 500]

# (Rust pin table name, value, decimal exponent E = floor(log10 c)).
CONSTS = [
    ("PI_PINS", lambda: +pi, 0),
    ("TWO_OVER_PI_PINS", lambda: 2 / pi, -1),
    ("LN2_PINS", lambda: log(2), -1),
    ("LN10_PINS", lambda: log(10), 0),
    ("E_PINS", lambda: +e, 0),
    ("TAN_PI_OVER_EIGHT_PINS", lambda: sqrt(2) - 1, -1),
]


def scaled_floor(value_fn, exponent: int, n: int, slack: int) -> int:
    """floor(c * 10^(n - 1 - E)) computed at `n + slack` decimal places."""
    mp.dps = n + slack
    return int(mp.floor(value_fn() * mpf(10) ** (n - 1 - exponent)))


def digits(value_fn, exponent: int, n: int) -> str:
    """The first `n` significant digits, cross-checked at two precisions."""
    low = scaled_floor(value_fn, exponent, n, 40)
    high = scaled_floor(value_fn, exponent, n, 90)
    assert low == high, f"precision-sensitive at n={n}: {low} != {high}"
    s = str(low)
    assert len(s) == n, f"want {n} digits, got {len(s)}"
    return s


def check_exponent(value_fn, exponent: int) -> None:
    """Guard the E claim in CONSTS against the actual magnitude."""
    mp.dps = 60
    v = value_fn()
    assert mpf(10) ** exponent <= v < mpf(10) ** (exponent + 1), f"bad E: {v}"


def main() -> None:
    print("// Generated by tools/gen_bigconst_oracle.py (mpmath).")
    for name, value_fn, exponent in CONSTS:
        check_exponent(value_fn, exponent)
        print(f"const {name}: [(u64, &str); {len(DEPTHS)}] = [")
        for n in DEPTHS:
            print(f'    ({n}, "{digits(value_fn, exponent, n)}"),')
        print("];")


if __name__ == "__main__":
    main()
