"""Generate Payne-Hanek constants for src/math/argred.rs.

Output format is Rust source ready to paste into argred.rs:
  - TWO_OVER_PI_DIGITS  (number of decimal digits in 2/π we store)
  - TWO_OVER_PI         (packed base-10^9 limbs, MSD-first within each limb)
  - PI_OVER_TWO_STR     (extended-precision π/2 as a decimal literal)
"""
import sys
sys.set_int_max_str_digits(100000)
from mpmath import mp, mpf

# Storage budget for 2/π:
#   Decimal128 max exponent for normalised input is ~ +6111 (coefficient
#   in [10^33, 10^34), so |x| < 10^{6145}). To recover the integer part
#   mod 4 and the fractional part to ~38 digits for any such x, the table
#   needs ~6145 digits at minimum. Round up to 6300 for headroom.
TWO_OVER_PI_DIGITS = 6300

# π/2 stored to 80 digits — multiplied by |y| ≤ 1/2 then rounded back to
# 34 digits. 46 guard digits is plenty.
PI_OVER_TWO_DIGITS = 80


def two_over_pi_decimal_digits(n: int) -> str:
    """Return the first `n` digits of 2/π after the decimal point.

    2/π = 0.6366197723... so digit 1 is '6', digit 2 is '3', etc.
    """
    # Use 50 digits of slack for the division.
    mp.dps = n + 50
    val = 2 / mp.pi
    # mpmath nstr gives "0.6366..." in scientific or fixed; mp.mpf -> str
    # uses fixed notation up to a point. Safer to multiply by 10^n and
    # take the integer part.
    scaled = val * mpf(10) ** n
    digits = mp.nstr(scaled, n + 5, strip_zeros=False)
    # nstr can return "6.3661977...e+xxxx"; instead, use floor(scaled).
    int_part = int(scaled)
    s = str(int_part)
    # Pad on the left with zeros if leading zeros got stripped (shouldn't
    # happen for 2/π, but be defensive).
    s = s.rjust(n, "0")
    assert len(s) == n, f"want {n} digits, got {len(s)}"
    assert s[0] == "6", f"first digit of 2/π should be 6, got {s[0]}"
    return s


def pi_over_two_decimal(n: int) -> str:
    mp.dps = n + 30
    val = mp.pi / 2
    # π/2 ≈ 1.5707963... so 1 integer digit + (n - 1) fractional.
    scaled = val * mpf(10) ** (n - 1)
    int_part = int(scaled)
    s = str(int_part)
    s = s.rjust(n, "0")
    assert s[0] == "1", f"first digit of π/2 should be 1, got {s[0]}"
    return f"{s[0]}.{s[1:]}"


def pack_base_10p9(digits: str) -> list[int]:
    """Pack decimal digits into base-10^9 u32 limbs, MSD-first within each limb.

    Final limb is right-padded with zeros to 9 digits' worth of place value.
    """
    limbs = []
    for i in range(0, len(digits), 9):
        chunk = digits[i:i + 9]
        # Right-pad with zeros so a short trailing chunk represents the same
        # numeric value as if we'd taken 9 digits.
        chunk = chunk.ljust(9, "0")
        limbs.append(int(chunk))
    return limbs


def emit_packed_array(name: str, limbs: list[int], n_digits: int) -> str:
    out = []
    out.append(f"pub(super) const {name}_DIGITS: usize = {n_digits};")
    out.append(f"pub(super) const {name}: &[u32; {len(limbs)}] = &[")
    for i in range(0, len(limbs), 8):
        row = limbs[i:i + 8]
        pieces = ", ".join(f"{w:>9}" for w in row)
        out.append(f"    {pieces},")
    out.append("];")
    return "\n".join(out)


def main():
    two_over_pi = two_over_pi_decimal_digits(TWO_OVER_PI_DIGITS)
    limbs = pack_base_10p9(two_over_pi)
    pi_over_two = pi_over_two_decimal(PI_OVER_TWO_DIGITS)

    print(f"// Auto-generated by tools/gen_argred.py — do not edit by hand.")
    print(f"// 2/π first 40 digits: 0.{two_over_pi[:40]}…")
    print()
    print(emit_packed_array("TWO_OVER_PI", limbs, TWO_OVER_PI_DIGITS))
    print()
    print(f"pub(super) const PI_OVER_TWO_STR: &str = \"{pi_over_two}\";")


if __name__ == "__main__":
    main()
