#!/usr/bin/env python3
"""Generate the margin lockstep table pinning ferrodec-campaign's
boundary distance primitive to the corpus generator's margin
definitions (ADR-0059, lane plan S1).

For each row the script evaluates gen_transcend_vectors.tie_margin and
.directed_margin on the exact Fraction value of a 50 digit coefficient,
then ASSERTS the integer tail formulation (T = coef50 mod 10^w) against
those floats before emitting. The committed table therefore certifies,
at generation time, that the gtv Fraction normalization and the integer
formulation are the same function; the Rust side
(ferrodec-campaign/tests/margin_lockstep.rs) pins its own integers to
the emitted ones exactly. Chain: gtv margins <-> (assert here) <->
integers <-> (Rust test) <-> boundary_distances.

Deterministic: fixed seed, no timestamps. Output:
ferrodec-campaign/tests/vectors/margin_lockstep.txt

Row format:
  prec exp coef50 grid_x2 tie_x2 directed_margin tie_margin
"""

import os
import random
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_transcend_vectors as gtv  # noqa: E402

SEED = 0xFDCB6 ^ 0x10C57E9
PRECS = (7, 16, 34)
EXPS = (-49, 0, 17)
RANDOM_PER_PREC = 12
OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "ferrodec-campaign",
    "tests",
    "vectors",
    "margin_lockstep.txt",
)


def adversarial_tails(w):
    half = 5 * 10 ** (w - 1)
    return [
        0,                # exact grid point
        1,                # one unit above the grid
        2,
        half - 1,         # one unit below the tie
        half,             # exact tie
        half + 1,
        10 ** w - 2,
        10 ** w - 1,      # one unit below the next grid point
        10 ** (w - 1),    # a decade inside the tail
        3 * 10 ** (w - 1),
    ]


def main():
    rng = random.Random(SEED)
    lines = [
        "# generated by tools/gen_margin_lockstep.py; do not edit",
        "# seed 0x%X; row: prec exp coef50 grid_x2 tie_x2 directed_margin tie_margin" % SEED,
        "# grid_x2 = 2*min(T, 10^w - T), tie_x2 = |2*T - 10^w|, T = coef50 mod 10^w,",
        "# w = 50 - prec; units of 10^-w/2 ULP. Floats are the gtv function outputs.",
    ]
    total = 0
    for p in PRECS:
        w = 50 - p
        tails = adversarial_tails(w) + [rng.randrange(10 ** w) for _ in range(RANDOM_PER_PREC)]
        for i, t in enumerate(tails):
            lead = rng.randrange(10 ** (49 - w), 10 ** (50 - w))
            coef50 = lead * 10 ** w + t
            assert len(str(coef50)) == 50
            exp = EXPS[i % len(EXPS)]
            v = Fraction(coef50) * (Fraction(10) ** exp)
            m_grid = gtv.directed_margin(v, p)
            m_tie = gtv.tie_margin(v, p)
            frac = Fraction(t, 10 ** w)
            assert m_grid == float(min(frac, 1 - frac)), (p, t)
            assert m_tie == float(abs(frac - Fraction(1, 2))), (p, t)
            grid_x2 = 2 * min(t, 10 ** w - t)
            tie_x2 = abs(2 * t - 10 ** w)
            lines.append("%d %d %d %d %d %r %r" % (p, exp, coef50, grid_x2, tie_x2, m_grid, m_tie))
            total += 1
    with open(OUT, "w", encoding="ascii") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d rows to %s" % (total, OUT))


if __name__ == "__main__":
    main()
