//! Moved from `ferrodec/src/math/argred.rs` @ commit 82a7fe1 (P0a.2 c7).
//! Behaviour-neutral: genericized over [`DecimalFormat`]; the
//! `Decimal128` instantiation is byte-identical to the pre-move kernel.
//!
//! Payne-Hanek argument reduction for `sin` / `cos`.
//!
//! ## Why
//!
//! The naive reduction `r = x − round(x / (π/2)) · (π/2)` works while
//! `|x|` is small enough that the cancellation in the subtraction
//! leaves at least 34 good digits. For `Decimal128`'s 34-digit
//! envelope that holds up to `|x| ≈ 10^9`; past that, more digits of
//! `π/2` get cancelled out than the native arithmetic carries, and
//! `r` rapidly loses meaning.
//!
//! ## Algorithm
//!
//! Payne and Hanek (1983, [doi:10.1145/1057600.1057602]) observed that the
//! cancellation is itself the reduction — multiplying `x` by an
//! extended-precision `2/π` and discarding the integer part gives the
//! reduced argument *without* any catastrophic subtraction. The product
//! only needs digits of `2/π` in a narrow window around the
//! integer / fraction boundary of `x · 2/π`, so storage scales linearly
//! with the input's exponent rather than exponentially with the loss
//! of precision.
//!
//! For `Decimal128` the maximum magnitude is `≈ 10^{6145}`, so we
//! embed `2/π` to 6 408 decimal digits (≈ 2.9 KB in flash, lives in
//! `.rodata`; sized for the widest reader, the rung 2 window below).
//! Each rung 1 call extracts a ~78-digit window indexed by the input's
//! unbiased exponent, multiplies by the 34-digit coefficient
//! into a `U384`, and reads the integer part `mod 4` and the leading
//! ~38 fractional digits directly out of the result. The fractional
//! part is then multiplied by a 38-digit truncated `π/2` constant
//! (`PI_OVER_TWO_COEF_38`, derived from and pinned against the
//! 120-digit `table::PI_OVER_TWO_STR` reference) to yield `r` with 1-2
//! ULP of error against the true reduction. The 120-digit string is a
//! derivation reference only; the rung 1 reduction reads the 38-digit
//! truncation, whose truncation-error discharge that constant's doc
//! records honestly (fd-aqs.10).
//!
//! `reduce_wide` (ADR-0059 M6) is the rung 2 sibling: a ~182-digit
//! window in `U768`, 143 fractional digits, and a 115-digit truncated
//! `π/2`, delivering the residual into `Extended2` with up to 110
//! surviving digits; its truncation discharge is analytic, not
//! empirical (< 10^-114 relative).
//!
//! `reduce_dyn` (M8b, behind the `unbounded-ladder` feature) is the
//! third sibling: the same pipeline with every width a function of the
//! rung's runtime precision `p`, and both constants computed per call
//! rather than read from storage. The table below cannot serve it — a
//! stored table caps the precision a rung can reach, and the Ziv
//! driver's doubling has no cap — so the `2/π` digits come from
//! `ferrodec_multiword::bigconst::two_over_pi_digits` and the `π/2`
//! coefficient from `bigconst::pi_digits`.
//!
//! ## Storage budget for the table
//!
//! The rung 1 window is `d_{q-1} … d_{q + 113}` and the rung 2 window
//! `d_{q-1} … d_{q + 180}`, where `q` is the unbiased exponent
//! (`biased_exp − BIAS`). With `q_max = +6111` (largest representable
//! unbiased exponent for a normalised coefficient) the deepest read is
//! `d_{6291}`, so 6 408 digits (712 whole base-10^9 limbs) gives 117
//! digits of headroom.
//!
//! ## Sign and rounding
//!
//! [`reduce`] takes an absolute value (sign separated by the caller)
//! and returns `k = round(|x| · 2/π) mod 4` plus the residual `r`,
//! where `|x| − k · π/2 = r` and `|r| ≤ π/4 + 2 · ULP(π/4)`. Callers
//! must adjust `k` and the residual sign for negative inputs (see
//! `sincos.rs`).

use crate::extended::{ExtNum, Extended};
use crate::extended2::Extended2;
#[cfg(feature = "unbounded-ladder")]
use crate::extended_dyn::ExtendedDyn;
use crate::format::DecimalFormat;
use ferrodec_ieee::Status;
use ferrodec_ieee::{decimal_digit_count_u128 as decimal_digit_count, IeeeDecodedClass as Class};
#[cfg(feature = "unbounded-ladder")]
use ferrodec_multiword::{bigconst, DecBig};
use ferrodec_multiword::{
    u256::widening_mul_u128, u768::u384_mul_u384_to_u768, U256, U384, U512, U768,
};

mod table {
    // Auto-generated by tools/gen_argred.py — to regenerate run:
    //   nix-shell -p python3Packages.mpmath --run \
    //     'python3 tools/gen_argred.py' > /tmp/argred_consts.rs
    // and paste the body here.
    //
    // 2/π first 40 digits: 0.6366197723675813430755350534900574481378…

    pub(super) const TWO_OVER_PI_DIGITS: usize = 6408;
    pub(super) const TWO_OVER_PI: &[u32; 712] = &[
        636619772, 367581343, 75535053, 490057448, 137838582, 961825794, 990669376, 235587190,
        536906140, 360455211, 65012343, 824291370, 907031832, 147571647, 384458314, 611511869,
        642926799, 356916959, 867749636, 310292310, 985587701, 230754869, 571584869, 590646773,
        449560966, 894516047, 329520456, 890799022, 863761847, 560347610, 695824481, 957643747,
        751376342, 114892399, 785773600, 994689390, 957838443, 593292387, 132299624, 667945851,
        218797794, 608751526, 299146267, 856964155, 983496557, 394439935, 472396799, 849771502,
        340684715, 433724470, 75068642, 186190147, 952038957, 841459037, 335072237, 209977986,
        541221308, 627102012, 881299111, 265588664, 91786992, 478392663, 362424067, 212143992,
        535647949, 995331146, 617741119, 20280064, 962710257, 555398285, 243520488, 797504590,
        725511058, 951562532, 272185831, 913927045, 249709256, 279843100, 98001191, 39428356,
        227611187, 140526100, 840065270, 984083699, 246424962, 245824812, 585936356, 993836765,
        740846301, 630224803, 486106427, 208868636, 563029898, 330890390, 985141599, 500621317,
        563255927, 89637433, 19188293, 314876162, 799903630, 630831397, 388157435, 931234869,
        370256146, 758046650, 182823773, 310525074, 600104490, 871884612, 845039801, 754671780,
        150502243, 345268467, 810390325, 128997664, 933372580, 424494147, 514252454, 546768668,
        568278987, 840517002, 313344212, 478434378, 39358226, 874839818, 986041726, 495262070,
        323357771, 919883998, 21017550, 264517783, 533227384, 203141166, 60564161, 957195402,
        555264310, 478797229, 364155998, 314767562, 392374951, 88247501, 728908757, 205465021,
        44955121, 550155524, 427256270, 617363313, 114107733, 707198224, 283161544, 241410955,
        984980503, 982997105, 188094376, 382337204, 659318564, 742310849, 623017797, 828087159,
        79169637, 961309179, 80866598, 414261272, 614176015, 362759498, 870766355, 52763866,
        27857619, 107882750, 734627112, 419119181, 801413583, 33207527, 354751751, 64499259,
        812239862, 320876334, 395004140, 508516172, 926321994, 878747511, 37862653, 848841368,
        177634219, 914015170, 954777174, 146477511, 317149437, 513738812, 920948583, 351694228,
        474545367, 717840732, 729167856, 660035132, 317325413, 991163989, 834597161, 69802439,
        574756378, 353220134, 812215221, 892492863, 237727907, 41291325, 256759238, 999289753,
        340697427, 959390004, 158002735, 520159146, 894398432, 96010956, 43499819, 419151694,
        273044559, 795613075, 989708333, 984459683, 315615107, 138972142, 18273824, 334685917,
        233826893, 308141941, 570224808, 347357296, 398248847, 13273576, 83883174, 283099861,
        995234744, 265443874, 647868149, 898168411, 324877007, 384899339, 964644598, 266224151,
        878704559, 725131984, 310433111, 960403132, 144009353, 91951634, 160955046, 229781723,
        704047640, 217351993, 556186196, 849931806, 428291412, 20908840, 944070093, 252692719,
        37244201, 312620437, 495654558, 581223170, 428720334, 471819506, 898583921, 895909169,
        792436803, 748503147, 673331583, 545135961, 743474666, 559026937, 805638014, 549308766,
        972455522, 655322903, 692110389, 380242192, 851112148, 261351132, 128683950, 939866273,
        963201307, 954026967, 165858734, 33126467, 413257344, 642923980, 599412479, 278935033,
        776839366, 623816609, 2573577, 251457761, 535534246, 35190865, 800682588, 270075098,
        242366434, 867431431, 756904939, 25326844, 531994623, 766387562, 879402754, 976920230,
        76790822, 760152873, 570248813, 549694145, 27233416, 626069188, 435246887, 183747330,
        259540749, 998994834, 212466393, 224405568, 578178406, 459538110, 810045644, 280994086,
        958980415, 466945615, 491440398, 699572694, 247248284, 696191559, 747554622, 769231394,
        9222822, 857625455, 452809474, 80429640, 229943691, 244628878, 720159129, 903812006,
        678340884, 921385675, 94601741, 870585826, 263887604, 492339068, 397238834, 365134586,
        676767107, 755165733, 262266026, 792528656, 608403582, 846914495, 370428271, 380704044,
        538032027, 979073689, 427958499, 522063103, 923813588, 323419002, 390145062, 596137577,
        816823271, 545742732, 168001260, 382378973, 757010179, 402699657, 163459005, 769213285,
        329827804, 653978271, 15757696, 144362175, 334211316, 973688139, 793746460, 586529144,
        99106666, 419812562, 629374302, 120563633, 119523659, 146773739, 690950410, 539991319,
        828072647, 857284932, 561903051, 589936331, 564696389, 913055159, 672679975, 794999086,
        79592749, 66517840, 732215833, 310083694, 540274155, 569138729, 890398901, 132030674,
        277503346, 388916792, 977189896, 246552732, 455833226, 977394067, 714389532, 949570649,
        609738007, 991239761, 608758453, 933709445, 470579965, 530861666, 425369931, 745496740,
        244904434, 452847994, 533851388, 397673597, 709718236, 625133359, 619215284, 700046448,
        466688207, 650317214, 211716964, 537612464, 536449981, 273543707, 833961775, 387231396,
        389593123, 542118818, 61221596, 560395479, 536353461, 934660889, 867449634, 901605616,
        36471496, 848818092, 301338958, 901525976, 155367623, 473692463, 785290977, 356264500,
        649572425, 132781295, 533568526, 138225526, 47008140, 434983823, 280449501, 743907262,
        136074962, 957736145, 359121552, 688401812, 676731807, 795183670, 695816711, 516974110,
        469628984, 237566410, 929131517, 872774596, 515798859, 813730210, 894366637, 192289919,
        943224507, 602932875, 378107177, 340182320, 780997026, 522481950, 646453746, 135968115,
        18083422, 137657639, 620519309, 98186364, 725288931, 362046664, 626028393, 502297349,
        181945248, 164486865, 523662424, 644662928, 333224, 458424725, 121305034, 783806409,
        852866455, 430645921, 887973083, 108526576, 480637984, 44253132, 208303833, 394012203,
        163823399, 319287469, 611593542, 55329582, 808323055, 902017169, 39390588, 284065707,
        897538017, 236663458, 113441299, 734417418, 628950231, 664546529, 648183123, 987886265,
        360886352, 218317725, 313112022, 98452835, 560749684, 843697956, 416402086, 198723884,
        548830160, 228438536, 265725429, 817596639, 77743155, 683173702, 471132088, 948045945,
        699700956, 994914852, 528087066, 944302658, 239309043, 829662640, 937514974, 516528438,
        994358860, 285229564, 162905741, 656718822, 889061919, 215260510, 383164960, 101378721,
        928810469, 369196004, 81932249, 852135185, 898712762, 7247321, 500615211, 518093733,
        678200854, 275908365, 162245727, 151516834, 482297999, 703159027, 607396841, 296825885,
        540764555, 259025608, 390422195, 831751405, 656165812, 206063358, 571293061, 624082413,
        247566346, 281088345, 1079665, 575006111, 549442432, 458227793, 684128963, 109090968,
        660545693, 746797086, 536123762, 122992261, 74037206, 635685476, 856572517, 485364246,
        286148562, 481591390, 473706011, 912314425, 67879843, 236736893, 905340190, 986876069,
        801805784, 665531384, 832963469, 438040948, 521161777, 511763414, 13781770, 533652250,
        522983805, 532124091, 725877378, 673314070, 653129660, 608407176, 905775828, 724868680,
        870259687, 857797586, 128888750, 633952978, 47637605, 362017728, 559434514, 484332717,
        575843377, 559207659, 149559089, 324114524, 52594782, 85048207, 311225397, 828474651,
        113026395, 324021406, 209266639, 375763608, 872252578, 180848519, 158937885, 954965033,
        72895440, 944108439, 924766082, 275293889, 593432053, 464273514, 531547171, 447892946,
        901442674, 86742528, 47795912, 293583367, 676266383, 354714117, 649674872, 869119500,
        244157842, 592783429, 824802435, 684913665, 577495386, 198359728, 113924945, 733864478,
        829297238, 183436293, 447514516, 252740066, 42507030, 740486543, 35478522, 980799688,
        4310670, 732378792, 599024907, 297391746, 852433648, 408780835, 979276497, 761950046,
        842367376, 559631557, 823100738, 486476166, 123738175, 211235754, 512292950, 314461071,
        188457329, 296787943, 122255052, 72353754, 656242870, 147328545, 51868489, 704377141,
        604438528, 730510604, 804680902, 117171586, 223784328, 197536362, 763042768, 15818584,
        766560086, 269344071, 638527491, 567994537, 364347612, 802318654, 841251444, 942795527,
    ];

    /// Reference value used to derive [`super::PI_OVER_TWO_COEF_38`].
    /// Kept here so the regenerator script can dump both the table and
    /// this string in one go, and so a unit test can pin the coefficient
    /// constant against it.
    #[allow(dead_code)]
    pub(super) const PI_OVER_TWO_STR: &str =
        "1.57079632679489661923132169163975144209858469968755291048747229615390820314310449931401741267105853399107404325664115332";

    /// Truncated 115-digit integer coefficient of π/2 as `U384` limbs
    /// (little-endian `u128` triple), the rung 2 counterpart of
    /// [`super::PI_OVER_TWO_COEF_38`]. Pinned against
    /// [`PI_OVER_TWO_STR`] by `pi_over_two_coef2_matches_string`.
    pub(super) const PI_OVER_TWO_COEF2_LO: u128 = 338116593859770840696669304177200717633;
    pub(super) const PI_OVER_TWO_COEF2_MID: u128 = 307524235238485890025282453579281015309;
    pub(super) const PI_OVER_TWO_COEF2_HI: u128 = 13565661843923943388123750214482931264;
}

// ----------------------------------------------------------------------------
// Algorithm constants. See module-level docs for derivation.

/// Fractional decimal digits we extract from the windowed product.
///
/// Sized to absorb up to 33 leading zeros (or 9s after rounding) in
/// the fractional residual when the input is within 1 ULP of an
/// integer multiple of π/2. The guaranteed surviving precision is
/// `FRAC_DIGITS − 33 = 43` significant digits in `y_signed`. That
/// is below `EXT_PRECISION = 50` of the downstream `Extended`
/// envelope, but comfortably above Decimal128's 34-digit boundary
/// (the relevant margin for callers): `43 − 34 = 9` headroom digits
/// at the worst case.
///
/// The 2026-05-10 six-agent review flagged the 9-digit margin as
/// "tight". Investigation during Slice E found the current budget
/// is empirically sufficient (the `property_sincos_large` suite
/// passes at 1 ULP across magnitudes through 1e500), so no bump
/// landed in 1.15. Bumping `FRAC_DIGITS` past 77 requires switching
/// the windowed product machinery from U256 to U384 (10^78 exceeds
/// U256's ~1.16 × 10^77 capacity); the refactor is well-supported
/// by the existing `u384_mul_u128_to_u512` helper but is deferred
/// until a failing high-magnitude case surfaces.
const FRAC_DIGITS: u32 = 76;
/// Extra digits below the precision window to absorb truncation
/// carries from the unread tail of `2/π`.
const CARRY_GUARD: u32 = 4;
/// Combined offset added to `q` to compute the high end of the window
/// (so that `i_hi = q + I_HI_OFFSET`).
const I_HI_OFFSET: u32 = FRAC_DIGITS + 33 + CARRY_GUARD; // = 113

/// 38 leading decimal digits of π/2, parsed as a u128 (truncated, not
/// rounded — pinned to [`table::PI_OVER_TWO_STR`] by
/// `pi_over_two_coef_matches_string`). Multiplied by the extracted
/// fractional residual (also up to 38 digits) to produce
/// `r = y · π/2` to ~75 digits before final rounding to 34.
///
/// Truncation-error discharge (fd-aqs.10, honest amendment of
/// ADR-0032). The truncation introduces ≤ 10^{-37} relative error in
/// π/2, which after multiplying by `|y| ≤ 0.5` and rounding `r` to 34
/// digits gives a *loose analytic* upper bound of ≤ 10^{-3} ULP. That
/// analytic bound is larger than the worst Decimal128 `cos` sampled
/// half-ULP margin (4.051 × 10^{-4} ULP), so it does not by itself
/// discharge the correctly-rounded obligation at Decimal128 trig. The
/// *measured* truncation contribution is ≤ ~6.3 × 10^{-5} ULP — an
/// order of magnitude below that margin — and the truncation bias is
/// one-sided and coherent across the three formats, so the reduction
/// perturbs no sampled correctly-rounded result. This is an empirical
/// discharge against sampled margins, not a fully analytic one; the
/// route to an analytic bound is the 80-digit U384 `π/2` path sketched
/// in the `FRAC_DIGITS` note, deferred until a failing high-magnitude
/// case surfaces.
const PI_OVER_TWO_COEF_38: u128 = 15_707_963_267_948_966_192_313_216_916_397_514_420;
const PI_OVER_TWO_EXP_38: i32 = -37;

// ----------------------------------------------------------------------------
// Rung 2 constants (ADR-0059, M6). The wide reduction mirrors the
// rung 1 pipeline with every width parameter scaled for the 110-digit
// Extended2 envelope; the 2/π table is shared.

/// Fractional decimal digits the rung 2 window extracts. Sized so the
/// worst-case 33 leading zeros (an input within 1 ULP of an integer
/// multiple of π/2) still leave `143 − 33 = 110` surviving significant
/// digits in `y_signed` — the full `EXT2_PRECISION` envelope, where
/// rung 1's 76 leaves 43 against its 50.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
const FRAC2_DIGITS: u32 = 143;
/// Window high-end offset for rung 2 (`i_hi = q + I_HI_OFFSET2`); the
/// same `33 + CARRY_GUARD` tail the rung 1 offset carries.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
const I_HI_OFFSET2: u32 = FRAC2_DIGITS + 33 + CARRY_GUARD; // = 180

/// 115 leading decimal digits of π/2 as a `U384` (truncated, not
/// rounded — pinned to [`table::PI_OVER_TWO_STR`] by
/// `pi_over_two_coef2_matches_string`). Multiplied by the (truncated
/// to ≤ 115 significant digit) fractional residual to produce
/// `r = y · π/2` before the collapse into `Extended2`.
///
/// Where the rung 1 38-digit truncation needed an *empirical*
/// discharge against sampled margins (fd-aqs.10), this one is
/// analytic: the truncation contributes < 10^-114 relative error in
/// π/2, three orders of magnitude below the 110-digit working
/// resolution and more than seventy below any format's half-ULP
/// margin — exactly the "80-digit U384 π/2 path" that constant's doc
/// deferred, delivered at 115 digits.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
const PI_OVER_TWO_COEF2: U384 = U384 {
    lo: table::PI_OVER_TWO_COEF2_LO,
    mid: table::PI_OVER_TWO_COEF2_MID,
    hi: table::PI_OVER_TWO_COEF2_HI,
};
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
const PI_OVER_TWO_EXP2: i32 = -114;

// ----------------------------------------------------------------------------
// Table accessors.

/// Decimal digit `i` of `2/π` (1-indexed; `i = 1` is the `6` in
/// `0.636…`). Returns `0` for indices beyond the table — callers must
/// pre-clip.
#[inline]
fn two_over_pi_digit(i: usize) -> u8 {
    debug_assert!((1..=table::TWO_OVER_PI_DIGITS).contains(&i));
    let idx = i - 1;
    let limb = table::TWO_OVER_PI[idx / 9];
    // Position 0 in a limb is the MSD (10^8), position 8 is the LSD.
    let pos = idx % 9;
    let shift = 10u32.pow(8 - pos as u32);
    ((limb / shift) % 10) as u8
}

// ----------------------------------------------------------------------------
// Multi-word multiplications used by the Payne-Hanek pipeline.

/// `a × b` for a `U384` and a `u128`, producing the **full** product
/// in a `U512`. Used by the windowed-product step where `a` is a
/// `2/π` window (up to ~115 decimal digits) and `b` is a 34-digit
/// Decimal128 coefficient — the product can grow up to ~149 digits,
/// which exceeds `U384`'s ~115-digit envelope.
#[inline]
fn u384_mul_u128_to_u512(a: U384, b: u128) -> U512 {
    // `widening_mul_u128` returns `(hi, lo)`.
    let (l_hi, l_lo) = widening_mul_u128(a.lo, b);
    let (m_hi, m_lo) = widening_mul_u128(a.mid, b);
    let (h_hi, h_lo) = widening_mul_u128(a.hi, b);

    // Layout in U512 (4 × u128 limbs lo / mid_lo / mid_hi / hi):
    //   lo     bits 0..127:    l_lo
    //   mid_lo bits 128..255:  l_hi + m_lo  (with carry into mid_hi)
    //   mid_hi bits 256..383:  m_hi + h_lo  (with carry from below + into hi)
    //   hi     bits 384..511:  h_hi (+ carry from below)
    let lo = l_lo;
    let (mid_lo, c1) = l_hi.overflowing_add(m_lo);
    let (mh_a, c2) = m_hi.overflowing_add(h_lo);
    let (mid_hi, c2b) = mh_a.overflowing_add(u128::from(c1));
    let hi = h_hi
        .wrapping_add(u128::from(c2))
        .wrapping_add(u128::from(c2b));

    U512 {
        lo,
        mid_lo,
        mid_hi,
        hi,
    }
}

/// `a × b` for a `U256` and a `u128`, producing the full product in a
/// `U384`. Used by `make_residual` to multiply the (up to 76-digit)
/// fractional magnitude by the 38-digit π/2 coefficient.
#[inline]
fn u256_mul_u128_to_u384(a: U256, b: u128) -> U384 {
    let (l_hi, l_lo) = widening_mul_u128(a.lo, b);
    let (h_hi, h_lo) = widening_mul_u128(a.hi, b);
    // Layout: lo = l_lo; mid = l_hi + h_lo; hi = h_hi + carry.
    let lo = l_lo;
    let (mid, c1) = l_hi.overflowing_add(h_lo);
    let hi = h_hi.wrapping_add(u128::from(c1));
    U384 { lo, mid, hi }
}

// ----------------------------------------------------------------------------
// Window extraction.

/// Build the integer `W = sum_{i=i_lo}^{i_hi} d_i · 10^{i_hi − i}`
/// where `d_i` is the i-th decimal digit of `2/π` (1-indexed).
fn extract_window(i_lo: usize, i_hi: usize) -> U384 {
    debug_assert!(i_lo >= 1 && i_hi <= table::TWO_OVER_PI_DIGITS && i_lo <= i_hi);
    let mut w = U384::ZERO;
    for i in i_lo..=i_hi {
        w = w.mul10();
        w = w.add(U384::from_u128(u128::from(two_over_pi_digit(i))));
    }
    w
}

// ----------------------------------------------------------------------------
// Splitting the windowed product into integer mod 4 and fractional part.

/// Result of the windowed multiplication, split into (integer mod 100,
/// fractional digits with high-order digit first, length).
struct Split {
    /// `floor(x · 2/π) mod 100`. Two decimal digits.
    floor_mod_100: u32,
    /// Decimal digits of the fractional part, MSD first. Length =
    /// `FRAC_DIGITS as usize`. Digit[0] is the 10^{-1} place; the
    /// last digit is the 10^{-FRAC_DIGITS} place.
    frac_digits: [u8; FRAC_DIGITS as usize],
}

/// Given `p = c · W` (a `U512`) and the implicit scale
/// `10^{-I_HI_OFFSET}`, peel off the digits that matter:
///   * positions `0 .. (I_HI_OFFSET − FRAC_DIGITS)` are the unread tail
///     (low-order noise + carry guard) — discarded.
///   * positions `(I_HI_OFFSET − FRAC_DIGITS) .. I_HI_OFFSET` are the
///     `FRAC_DIGITS` leading fractional digits (LSD first internally,
///     stored MSD-first in `frac_digits`).
///   * positions `I_HI_OFFSET .. I_HI_OFFSET + 2` are the integer mod 100.
fn split_product(mut p: U512) -> Split {
    let mut frac = [0u8; FRAC_DIGITS as usize];

    // Drop the unread tail. With FRAC_DIGITS = 76 and I_HI_OFFSET =
    // 113, that's 37 digits of low-order tail (33 from the
    // c-coefficient overlap below the fractional window, plus
    // CARRY_GUARD = 4).
    let drop = I_HI_OFFSET - FRAC_DIGITS;
    for _ in 0..drop {
        let (q, _) = p.div_rem10();
        p = q;
    }

    // Read the FRAC_DIGITS fractional digits (LSD first, then reverse).
    for slot in frac.iter_mut().rev() {
        let (q, d) = p.div_rem10();
        *slot = d as u8;
        p = q;
    }

    // Next 2 digits are the integer mod 100.
    let (q, d0) = p.div_rem10();
    let (_, d1) = q.div_rem10();
    let floor_mod_100 = d0 + d1 * 10;

    Split {
        floor_mod_100,
        frac_digits: frac,
    }
}

// ----------------------------------------------------------------------------
// Reconstruct the residual `r = y · π/2` as a `Decimal128`.

/// Build an `Extended` for `sign · y · π/2`, where `y` is given as the
/// fractional digit array with implicit scale `10^{-FRAC_DIGITS}`,
/// optionally minus `1` (when the rounding step chose to round up,
/// leaving a negative residual).
///
/// All `FRAC_DIGITS` digits of `y` are preserved into the windowed
/// product `y · π/2_38`, which then collapses to `Extended`'s
/// 50-digit envelope via `shift_right_to_u256`. The post-cancellation
/// effective precision in `y_mag` is at least 43 digits (76 − 33
/// leading zeros worst case), more than enough to round `r` faithfully.
fn make_residual<E: ExtNum>(
    ex: E,
    frac_digits: [u8; FRAC_DIGITS as usize],
    rounded_up: bool,
    sign: bool,
) -> E {
    // Pack all FRAC_DIGITS fractional digits into a U256. 76 digits ≈
    // 252 bits — fits comfortably (U256 holds up to 10^77).
    let mut y_coef = U256::ZERO;
    for &d in &frac_digits {
        y_coef = y_coef.mul10().add(U256::from_u128(u128::from(d)));
    }

    // For `round_up`: y_signed = (y_coef · 10^{-FRAC_DIGITS}) − 1, so
    // y_mag = 10^FRAC_DIGITS − y_coef. Build 10^FRAC_DIGITS in U256.
    let one_scaled = pow10_u256(FRAC_DIGITS);
    let mut y_signed_neg = false;
    let y_mag: U256 = if rounded_up {
        y_signed_neg = true;
        one_scaled.sub(y_coef)
    } else {
        y_coef
    };

    if y_mag.is_zero() {
        return ex.zero();
    }

    let net_sign = sign ^ y_signed_neg;

    // y_mag (≤ 76 digits) · PI_OVER_TWO_COEF_38 (38 digits) → U384
    // (up to 114 digits ≈ 378 bits, well inside U384's 384-bit cap).
    let coef = u256_mul_u128_to_u384(y_mag, PI_OVER_TWO_COEF_38);

    // Collapse U384 down to the U256 / Extended envelope, accumulating
    // dropped digits into a sticky bit so round-half-even can act on it.
    let (coef_u256, shift, sticky) = coef.shift_right_to_u256(false);

    // Combined exponent: y is at scale 10^{-FRAC_DIGITS}, π/2 at
    // 10^{PI_OVER_TWO_EXP_38} = 10^{-37}, plus the shift introduced by
    // the U384 → U256 collapse.
    let exp = -(FRAC_DIGITS as i32) + PI_OVER_TWO_EXP_38 + shift as i32;
    ex.from_components_with_sticky(coef_u256, exp, net_sign, sticky)
}

/// `10^k` as a `U256`. Bounded loop; caller keeps `k` ≤ 76 for the
/// `U256` envelope.
fn pow10_u256(k: u32) -> U256 {
    debug_assert!(k <= 76, "pow10_u256: k > 76 overflows U256");
    let mut v = U256::from_u128(1);
    let mut i = 0;
    while i < k {
        v = v.mul10();
        i += 1;
    }
    v
}

// ----------------------------------------------------------------------------
// Public entry point.

/// Reduce `|x|` for sin/cos. Caller must have already separated the
/// sign of `x`; this function operates on the absolute value.
///
/// Returns `(k mod 4, r, status)` such that
///
/// ```text
/// |x|  =  k · π/2 + r
/// |r| ≤ π/4 (with at most ~2 ULP overrun)
/// ```
///
/// `k` is `round(|x| · 2/π)` (round-half-away-from-zero — ties don't
/// arise in practice since the product is irrational).
///
/// `r` is returned at extended precision so the downstream Taylor
/// series in `sincos.rs` runs without losing the ~38 digits of
/// fractional residual that the windowed multiplication produced.
///
/// `x` must be finite. NaN, Infinity, and Zero are handled by the
/// caller before reaching here.
pub fn reduce<F: DecimalFormat>(x: F) -> (u32, Extended, Status) {
    reduce_body::<F, Extended>(Extended::ZERO, x)
}

/// Generic body of [`reduce`] (M4, ADR-0059): identical pipeline, with
/// the residual delivered into the caller's working-precision rung.
/// `ex` is that rung's exemplar (M8b): the receiver the residual
/// constructor reads its width from, never a value the result depends
/// on.
pub(crate) fn reduce_body<F: DecimalFormat, E: ExtNum>(ex: E, x: F) -> (u32, E, Status) {
    let cls = x.classify();
    let (biased_exp, c) = match cls {
        Class::Finite {
            biased_exp,
            coefficient,
            ..
        } => (biased_exp, coefficient),
        // Caller filters these out, but be defensive.
        _ => return (0, ex.from_format(x), Status::OK),
    };
    debug_assert!(c != 0);

    let q = biased_exp as i32 - F::BIAS; // unbiased exponent

    // Magnitude of |x|: |x| = c · 10^q. Decade ≈ q + digits(c) − 1.
    let dig_c = decimal_digit_count(c) as i32;
    let decade = q + dig_c - 1;

    // If |x| < π/4 ≈ 0.785, the reduction is trivially k = 0, r = |x|.
    // π/4 is between 10^{-1} and 1, so the safe shortcut is decade < -1
    // (i.e., |x| < 0.1 — well below π/4).
    if decade < -1 {
        // r = |x| at working precision.
        let r = ex.from_format(x).abs();
        return (0, r, Status::INEXACT);
    }

    // Compute the window [i_lo, i_hi] of `2/π` digits we need.
    //
    // Mathematically i_lo = q − 1 (so the window's MSD is the digit
    // that lands at the 10^1 place of `c · 2/π`). Clipped to ≥ 1.
    // i_hi = q + I_HI_OFFSET. Clipped to ≤ TWO_OVER_PI_DIGITS — but
    // we sized the table so this never trips for a normal Decimal128.
    let i_hi_signed = q + I_HI_OFFSET as i32;
    if i_hi_signed < 1 {
        // Window empty: |x · 2/π| ≪ 10^{-FRAC_DIGITS}, so k = 0.
        let r = ex.from_format(x).abs();
        return (0, r, Status::INEXACT);
    }
    let i_hi = (i_hi_signed as usize).min(table::TWO_OVER_PI_DIGITS);
    let i_lo_signed = q - 1;
    let i_lo = if i_lo_signed < 1 {
        1
    } else {
        i_lo_signed as usize
    };
    debug_assert!(i_lo <= i_hi);

    // W = window value as a U384 (≤ 78 decimal digits ≤ 2^259).
    let w = extract_window(i_lo, i_hi);

    // P = c × W. With FRAC_DIGITS = 76 the window is up to 115
    // digits and `c` is up to 34 digits — the product can reach
    // ~149 digits, exceeding `U384` (~115). The full product lives
    // in `U512` (~154 digits).
    let p = u384_mul_u128_to_u512(w, c);

    // The window value used the digits at positions i_lo..i_hi of 2/π,
    // which in `c · 10^q · 2/π` corresponds to the LSD of P sitting at
    // position 10^{q − i_hi} of x · 2/π. So P · 10^{q − i_hi} = the
    // windowed approximation to x · 2/π.
    //
    // We want round(x · 2/π) mod 4 and the fractional part. The
    // "decimal point" of P is positioned (i_hi − q) digits from the
    // right.
    //
    // For i_hi = q + I_HI_OFFSET (the unclipped case), this is exactly
    // I_HI_OFFSET = 113 (= FRAC_DIGITS + 33 + CARRY_GUARD = 76 + 33 + 4).
    // We rely on that: the table is sized so we never hit the i_hi clip
    // in practice (q_max + I_HI_OFFSET = 6111 + 113 = 6224 ≤ 6300, with
    // 76 digits of head-room before the table runs out). For the i_lo
    // clip (small q), shifting changes the window's interpretation:
    // dropping the digits below i_lo = 1 means we lose the d_0, d_{-1},
    // … positions, which don't exist because 2/π < 1. So the math works
    // out unchanged.
    debug_assert_eq!(
        i_hi - i_lo + 1,
        (i_hi_signed as usize - i_lo_signed.max(1) as usize) + 1
    );
    debug_assert!(i_hi as i32 - q == I_HI_OFFSET as i32);

    let split = split_product(p);

    // Decide whether the fractional part is ≥ 0.5: leading digit ≥ 5.
    let leading_frac = split.frac_digits[0];
    let round_up = leading_frac >= 5;

    let floor_mod_4 = split.floor_mod_100 % 4;
    let k_mod_4 = if round_up {
        (floor_mod_4 + 1) % 4
    } else {
        floor_mod_4
    };

    // Build r at extended precision. The caller passes the ABS value;
    // the residual sign is entirely determined by `round_up`.
    let r = make_residual(ex, split.frac_digits, round_up, false);
    (k_mod_4, r, Status::INEXACT)
}

// ----------------------------------------------------------------------------
// Rung 2: the wide reduction (ADR-0059, M6).
//
// Same Payne-Hanek pipeline as [`reduce_body`], with every buffer one
// width class up: the window lives in `U768` (≤ 182 digits), the
// windowed product `c × W` stays in `U768` (≤ 216 digits ≤ 231), the
// fractional residual carries `FRAC2_DIGITS = 143` digits, and the
// final multiply runs `y (≤ 115 digits) × π/2 (115 digits)` through
// `u384_mul_u384_to_u768`. Escalated calls re-run the reduction from
// the original input, so no rung 1 state is reused.

/// Build the rung 2 window `W` as a `U768` (up to 182 digits).
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
fn extract_window_wide(i_lo: usize, i_hi: usize) -> U768 {
    debug_assert!(i_lo >= 1 && i_hi <= table::TWO_OVER_PI_DIGITS && i_lo <= i_hi);
    let mut w = U768::ZERO;
    for i in i_lo..=i_hi {
        w = w.mul10();
        w = w.add(U768::from_u128(u128::from(two_over_pi_digit(i))));
    }
    w
}

/// Rung 2 sibling of [`Split`]: 143 fractional digits.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
struct SplitWide {
    floor_mod_100: u32,
    frac_digits: [u8; FRAC2_DIGITS as usize],
}

/// Rung 2 sibling of [`split_product`]: peel the `U768` windowed
/// product into integer-mod-100 and the 143 leading fractional digits,
/// discarding the same `33 + CARRY_GUARD`-digit unread tail.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
fn split_product_wide(mut p: U768) -> SplitWide {
    let mut frac = [0u8; FRAC2_DIGITS as usize];

    let drop = I_HI_OFFSET2 - FRAC2_DIGITS;
    for _ in 0..drop {
        let (q, _) = p.div_rem10();
        p = q;
    }

    for slot in frac.iter_mut().rev() {
        let (q, d) = p.div_rem10();
        *slot = d as u8;
        p = q;
    }

    let (q, d0) = p.div_rem10();
    let (_, d1) = q.div_rem10();
    let floor_mod_100 = d0 + d1 * 10;

    SplitWide {
        floor_mod_100,
        frac_digits: frac,
    }
}

/// Rung 2 sibling of [`make_residual`], delivering into [`Extended2`].
///
/// The 143-digit fractional magnitude exceeds every product buffer
/// when paired with the 115-digit π/2, so it is first truncated to at
/// most 115 significant digits with the dropped tail folded into a
/// sticky bit (a loss below 10^-114 relative — the same order as the
/// π/2 truncation itself, both inside the 110-digit envelope). The
/// worst-case 33-zero cancellation leaves 110 significant digits, in
/// which case nothing is dropped at all.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
fn make_residual_wide(
    frac_digits: [u8; FRAC2_DIGITS as usize],
    rounded_up: bool,
    sign: bool,
) -> Extended2 {
    // Pack all FRAC2_DIGITS fractional digits into a U768 (143 digits
    // ≪ the 231-digit capacity).
    let mut y_coef = U768::ZERO;
    for &d in &frac_digits {
        y_coef = y_coef.mul10().add(U768::from_u128(u128::from(d)));
    }

    let one_scaled = U768::from_u128(1).mul_pow10(FRAC2_DIGITS);
    let mut y_signed_neg = false;
    let y_mag: U768 = if rounded_up {
        y_signed_neg = true;
        one_scaled.sub(y_coef)
    } else {
        y_coef
    };

    if y_mag.is_zero() {
        return Extended2::ZERO;
    }

    let net_sign = sign ^ y_signed_neg;

    // Truncate y to ≤ 115 significant digits (sticky), so the product
    // below fits `u384_mul_u384_to_u768`'s 230-digit envelope.
    let dig_y = y_mag.decimal_digit_count();
    let drop_y = dig_y.saturating_sub(115);
    let mut y_trunc = y_mag;
    let mut sticky = false;
    let mut i = 0u32;
    while i < drop_y {
        let (q, r) = y_trunc.div_rem10();
        if r != 0 {
            sticky = true;
        }
        y_trunc = q;
        i += 1;
    }
    let y_u384 = u768_low_to_u384(y_trunc);

    // y (≤ 115 digits) · π/2 (115 digits) → ≤ 230 digits in U768.
    let prod = u384_mul_u384_to_u768(y_u384, PI_OVER_TWO_COEF2);

    // Collapse to the U384 / Extended2 envelope, folding dropped
    // digits into the sticky.
    let (coef_u384, shift, sticky_all) = prod.shift_right_to_u384(sticky);

    // Combined exponent: y at scale 10^{-FRAC2_DIGITS} shifted up by
    // the truncation, π/2 at 10^{PI_OVER_TWO_EXP2}, plus the collapse.
    let exp = -(FRAC2_DIGITS as i32) + drop_y as i32 + PI_OVER_TWO_EXP2 + shift as i32;
    Extended2::from_components_with_sticky(coef_u384, exp, net_sign, sticky_all)
}

/// Convert a `U768` known to fit 384 bits (≤ 115 decimal digits).
#[inline]
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
fn u768_low_to_u384(c: U768) -> U384 {
    debug_assert!(
        c.limbs[3] == 0 && c.limbs[4] == 0 && c.limbs[5] == 0,
        "u768_low_to_u384: upper limbs must be zero"
    );
    U384 {
        lo: c.limbs[0],
        mid: c.limbs[1],
        hi: c.limbs[2],
    }
}

/// Rung 2 reduction: `|x| = k · π/2 + r` with `r` delivered at
/// [`Extended2`] precision (up to 110 surviving digits against
/// rung 1's 43). Same contract as [`reduce`] otherwise; `x` finite,
/// sign separated by the caller.
#[allow(dead_code)] // reached at M8, when the ladder wires rung 2
pub(crate) fn reduce_wide<F: DecimalFormat>(x: F) -> (u32, Extended2, Status) {
    let cls = x.classify();
    let (biased_exp, c) = match cls {
        Class::Finite {
            biased_exp,
            coefficient,
            ..
        } => (biased_exp, coefficient),
        // Caller filters these out, but be defensive.
        _ => return (0, Extended2::from_format(x), Status::OK),
    };
    debug_assert!(c != 0);

    let q = biased_exp as i32 - F::BIAS;
    let dig_c = decimal_digit_count(c) as i32;
    let decade = q + dig_c - 1;

    // |x| < 0.1 ≪ π/4: trivially k = 0, r = |x|.
    if decade < -1 {
        let r = Extended2::from_format(x).abs();
        return (0, r, Status::INEXACT);
    }

    let i_hi_signed = q + I_HI_OFFSET2 as i32;
    if i_hi_signed < 1 {
        // Window empty: |x · 2/π| ≪ 10^{-FRAC2_DIGITS}, so k = 0.
        let r = Extended2::from_format(x).abs();
        return (0, r, Status::INEXACT);
    }
    let i_hi = (i_hi_signed as usize).min(table::TWO_OVER_PI_DIGITS);
    let i_lo_signed = q - 1;
    let i_lo = if i_lo_signed < 1 {
        1
    } else {
        i_lo_signed as usize
    };
    debug_assert!(i_lo <= i_hi);

    // W = window value as a U768 (≤ 182 digits). The table never clips
    // i_hi for a normal Decimal128: q_max + I_HI_OFFSET2 = 6111 + 180
    // = 6291 ≤ 6408, with 117 digits of headroom.
    let w = extract_window_wide(i_lo, i_hi);

    // P = c × W ≤ 34 + 182 = 216 digits — inside U768's 231.
    let p = w.mul_u128(c);

    debug_assert!(i_hi as i32 - q == I_HI_OFFSET2 as i32);

    let split = split_product_wide(p);

    let leading_frac = split.frac_digits[0];
    let round_up = leading_frac >= 5;

    let floor_mod_4 = split.floor_mod_100 % 4;
    let k_mod_4 = if round_up {
        (floor_mod_4 + 1) % 4
    } else {
        floor_mod_4
    };

    let r = make_residual_wide(split.frac_digits, round_up, false);
    (k_mod_4, r, Status::INEXACT)
}

// ----------------------------------------------------------------------------
// The unbounded rung: the runtime reduction (ADR-0059 M8b).
//
// [`reduce_dyn`] is [`reduce_wide`] with every width a function of the
// rung's runtime precision `p = ex.precision()` and both constants
// computed per call. Three things change and nothing else does:
//
//   * the `2/π` digits come from `bigconst::two_over_pi_digits(i_hi)`
//     instead of the 6 408-digit table, since a table caps the
//     precision a rung can reach and the Ziv driver's doubling has no
//     cap;
//   * the `π/2` coefficient comes from `bigconst::pi_digits` at
//     `p + 5` digits instead of a hand-curated literal;
//   * the coefficients live on the growable `DecBig` substrate, so
//     there is no fixed buffer to size and no `shift_right_to_*`
//     collapse — `ExtendedDyn::from_decbig_with_sticky` performs the
//     single rounding that ends the pipeline.
//
// Every width below reproduces its rung 2 constant at `p = 110`, which
// is what makes the dynamic rung a continuation of the ladder rather
// than a second policy; `reduce_dyn_agrees_with_reduce_wide` is the
// standing guard on that claim.

/// Fractional decimal digits the dynamic window extracts at working
/// precision `p`.
///
/// Derived exactly as the fixed rungs': the worst case is an input
/// within 1 ULP of an integer multiple of `π/2`, which cancels up to 33
/// leading digits of the fractional residual, so `p + 33` extracted
/// digits still leave `p` surviving significant digits — the rung's
/// full envelope, where rung 1's 76 leave 43 against its 50. At
/// `p = 110` this reproduces [`FRAC2_DIGITS`] = 143.
#[cfg(feature = "unbounded-ladder")]
const fn frac_digits_dyn(p: u32) -> u32 {
    p + 33
}

/// Window high-end offset at working precision `p`, so that
/// `i_hi = q + i_hi_offset_dyn(p)`.
///
/// The same `33 + CARRY_GUARD` tail the fixed offsets carry: 33 digits
/// of coefficient overlap below the fractional window (a format
/// coefficient is up to 34 digits wide, so the windowed product's low
/// 33 digits carry no information the kept fraction needs), plus
/// [`CARRY_GUARD`] = 4 digits absorbing the unread tail of `2/π`. The
/// offset is therefore `(p + 33) + 33 + 4 = p + 70`, reproducing
/// [`I_HI_OFFSET2`] = 180 at `p = 110`.
///
/// The M8b plan sketch quoted the read depth as `q + p + ~45`; the
/// exact rung 2 mirror derivation gives `q + p + 70`, and that is the
/// number the code uses.
///
/// The generator caps its depth at `bigconst::MAX_DIGITS = 100_000`,
/// and the deepest read is `q_max + p + 70 = 6181 + p`, so every input
/// stays inside the cap for `p ≤ 93_819`. The Ziv driver doubles from
/// 110, so the widths it can reach below `DynArena`'s own construction
/// cap of `99_993` are `110 · 2^k ≤ 56_320`; the generator's cap is
/// never the binding constraint in practice, and it panics loudly
/// rather than silently truncating if some future driver widens past
/// it.
#[cfg(feature = "unbounded-ladder")]
const fn i_hi_offset_dyn(p: u32) -> u32 {
    frac_digits_dyn(p) + 33 + CARRY_GUARD
}

/// The `p + 5` leading decimal digits of `π/2` as an integer, so that
/// `π/2 ≈ coef · 10^-(p + 4)`. The runtime sibling of
/// [`PI_OVER_TWO_COEF2`], which is exactly this value at `p = 110`
/// (115 digits, exponent −114).
///
/// Scale derivation. `D = pi_digits(p + 6)` is `floor(π · 10^(p + 5))`
/// up to the generator's documented ≤ 1 unit, so
/// `|D − π · 10^(p + 5)| < 2`. Integer halving floors, so
/// `|D/2 − (π/2) · 10^(p + 5)| < 1 + 1/2`. Dropping the last digit
/// divides that by ten and floors once more, giving
/// `|coef − (π/2) · 10^(p + 4)| < 1.5/10 + 1 = 1.15`: the coefficient
/// sits within **2** units of its last digit. `π/2 ≈ 1.5708` keeps
/// `(π/2) · 10^(p + 4)` at exactly `p + 5` digits, which is why that
/// last-digit drop is also what lands the requested width.
///
/// Truncation-error discharge (the M8b budget's `π/2` term).
/// `(π/2) · 10^(p + 4) > 1.5 · 10^(p + 4)`, so those 2 units are under
/// `1.4 · 10^-(p + 4)` of the value: the constant carries
/// **< 10^-(p + 3) relative error**. The residual `r = y · π/2`
/// inherits that 1:1, so the reduction's `π/2` term contributes
/// < 10^-(p + 3) relative to `r` — three orders below the rung's own
/// `10^-p` working resolution, and the formula restatement of rung 2's
/// analytic `< 10^-114` at 110 digits.
#[cfg(feature = "unbounded-ladder")]
fn pi_over_two_coef_dyn(p: u32) -> DecBig {
    let deeper = bigconst::pi_digits(u64::from(p) + 6);
    let halved = deeper.div_rem(&DecBig::from_u32(2)).0;
    halved.div_rem_pow10(1).0
}

/// Runtime sibling of [`make_residual_wide`], delivering into
/// [`ExtendedDyn`] at the arena's width.
///
/// `frac` is the extracted fractional magnitude at implicit scale
/// `10^-frac_dyn` (it may carry fewer than `frac_dyn` digits, since
/// leading zeros of the fraction are leading zeros of the integer);
/// `rounded_up` says the reduction chose the next multiple of `π/2`,
/// leaving a negative residual `y − 1`.
///
/// As at rung 2 the fractional magnitude is first truncated to at most
/// `p + 5` significant digits with the dropped tail folded into a
/// sticky bit. That truncation costs < 10^-(p + 4) relative — the same
/// order as the `π/2` constant's own, and below the `10^-p` working
/// resolution — and it keeps the final multiply at ~`2p + 10` digits
/// so the error argument is the fixed rung's verbatim. The worst-case
/// 33-zero cancellation leaves exactly `p` significant digits, in which
/// case nothing is dropped at all.
#[cfg(feature = "unbounded-ladder")]
fn make_residual_dyn(
    ex: ExtendedDyn<'_>,
    frac: DecBig,
    frac_dyn: u32,
    rounded_up: bool,
    sign: bool,
) -> ExtendedDyn<'_> {
    let p = ex.precision();

    // For `rounded_up`: y_signed = frac · 10^-frac_dyn − 1, so
    // y_mag = 10^frac_dyn − frac.
    let mut y_signed_neg = false;
    let y_mag = if rounded_up {
        y_signed_neg = true;
        DecBig::pow10(frac_dyn).sub(&frac)
    } else {
        frac
    };

    if y_mag.is_zero() {
        return ex.zero();
    }

    let net_sign = sign ^ y_signed_neg;

    // Truncate y to ≤ p + 5 significant digits, dropped tail into the
    // sticky the final rounding consumes.
    let dig_y = u32::try_from(y_mag.decimal_digit_count())
        .expect("the fractional window is at most p + 33 digits wide");
    let drop_y = dig_y.saturating_sub(p + 5);
    let (y_trunc, dropped) = y_mag.div_rem_pow10(drop_y);
    let sticky = !dropped.is_zero();

    // y (≤ p + 5 digits) · π/2 (p + 5 digits) → ≤ 2p + 10 digits.
    let prod = y_trunc.mul(&pi_over_two_coef_dyn(p));

    // Combined exponent: y at scale 10^-frac_dyn shifted up by the
    // truncation, π/2 at 10^-(p + 4). The growable substrate has no
    // collapse shift to add; `from_decbig_with_sticky` folds its own
    // rounding shift into the exponent it returns.
    let exp = -(frac_dyn as i32) + drop_y as i32 - (p as i32 + 4);
    ex.from_decbig_with_sticky(prod, exp, net_sign, sticky)
}

/// Runtime reduction: `|x| = k · π/2 + r` with `r` delivered at the
/// exemplar arena's runtime precision `p`. Same contract as [`reduce`]
/// otherwise; `x` finite, sign separated by the caller.
///
/// `ex` is the width exemplar (the M8b seam): the receiver the residual
/// constructor reads its arena and its precision from, never a value
/// the result depends on.
#[cfg(feature = "unbounded-ladder")]
pub(crate) fn reduce_dyn<F: DecimalFormat>(
    ex: ExtendedDyn<'_>,
    x: F,
) -> (u32, ExtendedDyn<'_>, Status) {
    let cls = x.classify();
    let (biased_exp, c) = match cls {
        Class::Finite {
            biased_exp,
            coefficient,
            ..
        } => (biased_exp, coefficient),
        // Caller filters these out, but be defensive.
        _ => return (0, ex.from_format(x), Status::OK),
    };
    debug_assert!(c != 0);

    let p = ex.precision();
    let frac_dyn = frac_digits_dyn(p);
    let offset = i_hi_offset_dyn(p);

    let q = biased_exp as i32 - F::BIAS;
    let dig_c = decimal_digit_count(c) as i32;
    let decade = q + dig_c - 1;

    // |x| < 0.1 ≪ π/4: trivially k = 0, r = |x|.
    if decade < -1 {
        let r = ex.from_format(x).abs();
        return (0, r, Status::INEXACT);
    }

    let i_hi_signed = q + offset as i32;
    if i_hi_signed < 1 {
        // Window empty: |x · 2/π| ≪ 10^-frac_dyn, so k = 0.
        let r = ex.from_format(x).abs();
        return (0, r, Status::INEXACT);
    }
    // Nothing clips the high end: there is no table to run out of, and
    // the generator produces exactly the digits asked for. The decade
    // guard above forces `q ≥ −dig_c ≥ −34`, so
    // `i_hi ≥ p + 70 − 34 ≥ 146` — comfortably above the generator's
    // `MIN_DIGITS = 8` floor, which is why no low-end clamp is needed
    // either.
    let i_hi = i_hi_signed as u32;
    let i_lo_signed = q - 1;
    let i_lo = if i_lo_signed < 1 {
        1
    } else {
        i_lo_signed as u32
    };
    debug_assert!(i_lo <= i_hi);

    // `two_over_pi_digits(i_hi)` is `floor((2/π) · 10^i_hi)` to within
    // one unit: an `i_hi`-digit integer whose digit `i` is the `i`-th
    // significant digit of 2/π. Since `2/π = 0.6366…` has a nonzero
    // first fractional digit, significant digit `i` IS fractional digit
    // `i` — the same 1-indexing `two_over_pi_digit` uses against the
    // static table, which `two_over_pi_generator_indexes_like_the_table`
    // pins.
    //
    // The window `W = D mod 10^(i_hi − i_lo + 1)` drops the digits more
    // significant than `d_{i_lo}`, exactly the ones
    // `extract_window_wide` never reads.
    let d = bigconst::two_over_pi_digits(u64::from(i_hi));
    let w = d.div_rem_pow10(i_hi - i_lo + 1).1;

    // W spans `i_hi − i_lo + 1 = offset + 2 = p + 72` digits (rung 2's
    // 182 at p = 110), so P = c × W reaches 34 + p + 72 = p + 106.
    let prod = w.mul(&DecBig::from_u128(c));

    // Why the discarded high digits cost nothing, and why the
    // generator's ≤ 1 unit costs nothing (the two truncation
    // discharges the M8b budget derivation reads).
    //
    // Write `A = 2/π` and `D` for the generated digits, so
    // `|A − D · 10^-i_hi| < 2 · 10^-i_hi`: one unit of the generator's
    // documented bound plus one of its own floor. Then
    //
    //     |x · A − c · D · 10^(q − i_hi)| < 2 · c · 10^(q − i_hi)
    //                                     = 2 · c · 10^-offset
    //                                     ≤ 2 · 10^-(p + 36)
    //
    // for every supported format (`c < 10^34`). The window step is an
    // exact integer congruence on top of that: with
    // `H = floor(D / 10^(i_hi − i_lo + 1))`,
    //
    //     c · D · 10^(q − i_hi) − c · W · 10^(q − i_hi)
    //         = c · H · 10^(q − i_lo + 1) = 100 · c · H
    //
    // in the unclipped case `i_lo = q − 1`, and `H = 0` outright in the
    // clipped case (`D` has exactly `i_hi` digits, and the window then
    // spans all of them). A multiple of 100 changes neither `k mod 4`
    // nor the fractional part, which is precisely why the integer is
    // read `mod 100` two digits up.
    //
    // So `P · 10^-offset` reproduces `x · 2/π` mod 100 to within
    // `2 · 10^-(p + 36)`, and the last fractional digit kept sits at
    // `10^-(p + 33)`: the combined truncation is ≤ 2 · 10^-3 of that
    // digit. `CARRY_GUARD = 4` unread guard digits are what pay for it.
    // Nothing here reasons about individual digit values, so the
    // generator's unit cannot be amplified by a borrow across the
    // window boundary.
    debug_assert!(i_hi as i32 - q == offset as i32);

    // Split: drop the `33 + CARRY_GUARD` unread tail, take the next
    // `frac_dyn` digits as the fraction, read the integer above it.
    let (kept, _) = prod.div_rem_pow10(offset - frac_dyn);
    let (int_part, frac) = kept.div_rem_pow10(frac_dyn);
    let floor_mod_100 = int_part
        .div_rem_pow10(2)
        .1
        .to_u128()
        .expect("two decimal digits fit u128") as u32;

    // The fractional part is ≥ 0.5 exactly when its leading digit (the
    // 10^-1 place) is ≥ 5, i.e. when `frac ≥ 5 · 10^(frac_dyn − 1)`.
    let half = DecBig::from_u32(5).mul_pow10(frac_dyn - 1);
    let round_up = frac.cmp_ref(&half) != core::cmp::Ordering::Less;

    let floor_mod_4 = floor_mod_100 % 4;
    let k_mod_4 = if round_up {
        (floor_mod_4 + 1) % 4
    } else {
        floor_mod_4
    };

    // The caller passes the ABS value; the residual sign is entirely
    // determined by `round_up`.
    let r = make_residual_dyn(ex, frac, frac_dyn, round_up, false);
    (k_mod_4, r, Status::INEXACT)
}

// ----------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    extern crate alloc;
    use super::*;

    #[test]
    fn first_digits_of_two_over_pi() {
        // 2/π = 0.63661977236758134307553505349005744813783858296183…
        let want = "63661977236758134307553505349005744813";
        for (i, ch) in want.char_indices() {
            let got = two_over_pi_digit(i + 1);
            let want_d = ch.to_digit(10).unwrap() as u8;
            assert_eq!(
                got,
                want_d,
                "digit {} mismatch: got {got}, want {want_d}",
                i + 1
            );
        }
    }

    #[test]
    fn pi_over_two_coef_matches_string() {
        // PI_OVER_TWO_COEF_38 must be the 38 leading decimal digits of
        // table::PI_OVER_TWO_STR (without the decimal point), parsed as
        // a u128.
        let s = table::PI_OVER_TWO_STR
            .chars()
            .filter(char::is_ascii_digit)
            .take(38)
            .collect::<alloc::string::String>();
        let derived: u128 = s.parse().unwrap();
        assert_eq!(derived, PI_OVER_TWO_COEF_38);
    }

    // -----------------------------------------------------------------
    // Rung 2 (ADR-0059, M6).

    #[test]
    fn pi_over_two_coef2_matches_string() {
        // PI_OVER_TWO_COEF2 must be the 115 leading decimal digits of
        // table::PI_OVER_TWO_STR, built independently here digit by
        // digit.
        let mut derived = U384::ZERO;
        let mut count = 0usize;
        for ch in table::PI_OVER_TWO_STR.chars() {
            if let Some(d) = ch.to_digit(10) {
                if count == 115 {
                    break;
                }
                derived = derived.mul10().add(U384::from_u128(u128::from(d)));
                count += 1;
            }
        }
        assert_eq!(count, 115, "PI_OVER_TWO_STR carries at least 115 digits");
        assert_eq!(derived, PI_OVER_TWO_COEF2);
    }

    #[test]
    fn wide_table_headroom_never_clips() {
        // The rung 2 window's deepest read for a normal Decimal128:
        // q_max + I_HI_OFFSET2 must stay inside the table.
        let deepest = 6111 + I_HI_OFFSET2 as usize;
        assert!(deepest <= table::TWO_OVER_PI_DIGITS);
        // And the rung 1 window a fortiori.
        assert!(6111 + I_HI_OFFSET as usize <= table::TWO_OVER_PI_DIGITS);
    }

    /// The load-bearing M6 check: rung 1 and rung 2 reduce the SAME
    /// inputs to the same quadrant, and their residuals agree to the
    /// rung 1 fidelity floor. The two pipelines share only the 2/π
    /// digit table; window sizes, product widths, residual packing,
    /// and the π/2 multiply all differ, so agreement to ~40 digits on
    /// inputs spanning the full exponent range is strong evidence
    /// against both width bugs and table-extension bugs.
    #[test]
    fn reduce_wide_agrees_with_rung1() {
        use crate::mock_format::ValueFmt128;

        let coefs: [u128; 5] = [
            1,
            3_141_592_653_589_793_238_462_643_383_279_503, // ~π-flavoured 34 digits
            9_999_999_999_999_999_999_999_999_999_999_999,
            2_718_281_828_459_045_235_360_287_471_352_662,
            7_071_067_811_865_475_244_008_443_621_048_490,
        ];
        let exps: [i32; 12] = [-40, -33, -30, -10, -1, 0, 5, 50, 500, 3000, 6000, 6077];

        let quarter_pi_loose = Extended2::parse_str("0.7854");
        let mut checked = 0u32;
        for &coef in &coefs {
            for &exp in &exps {
                // Keep the value's adjusted exponent in the normal
                // range the reduction contracts cover.
                let x = ValueFmt128 {
                    coef,
                    exp,
                    sign: false,
                };
                let (k1, r1, s1) = reduce_body::<ValueFmt128, Extended>(Extended::ZERO, x);
                let (k2, r2, s2) = reduce_wide::<ValueFmt128>(x);
                assert_eq!(k1, k2, "quadrant split for coef={coef} exp={exp}");
                assert_eq!(s1, s2, "status for coef={coef} exp={exp}");

                // |r2| ≤ π/4 (loose bound; the ±2 ULP overrun of the
                // contract is far below the slack in 0.7854).
                assert!(
                    r2.abs().cmp(quarter_pi_loose) != core::cmp::Ordering::Greater,
                    "wide residual out of range for coef={coef} exp={exp}"
                );

                // Residual agreement: |r1 − r2| relative to |r2| below
                // 10^-36. The binding term is rung 1's own 38-digit
                // truncated π/2 multiply (the fd-aqs.10 discharge:
                // ~10^-38 relative, one-sided) — measured directly by
                // this differential at e.g. x = 0.1, where rung 2 is
                // exact and rung 1 lands 6.3e-38 relative away. The
                // 10^-36 bound gives that term two orders of slack
                // while still catching any genuine width or table bug
                // (those diverge at the leading digits, not the 38th).
                let r1_wide = Extended2::from_extended(r1);
                let d = r1_wide.sub(r2);
                if d.is_zero() {
                    checked += 1;
                    continue;
                }
                assert!(
                    !r2.is_zero(),
                    "rung disagreement about a zero residual for coef={coef} exp={exp}"
                );
                let d_adj = d.exp + d.coef.decimal_digit_count() as i32 - 1;
                let r_adj = r2.exp + r2.coef.decimal_digit_count() as i32 - 1;
                assert!(
                    d_adj <= r_adj - 36,
                    "residual divergence above 10^-36 relative for coef={coef} exp={exp}: \
                     r1={r1:?} r2={r2:?}"
                );
                checked += 1;
            }
        }
        assert_eq!(checked, 60, "every pair exercised");
    }

    /// The wide reduction's raison d'être: an input adjacent to a
    /// multiple of π/2 cancels ~33 leading digits, and rung 2 must
    /// still deliver ~110 surviving digits where rung 1 has ~43. The
    /// 34-digit truncation of π/2 itself is the deepest such input:
    /// its true residual is `x − π/2 ≈ −4.4e-34`, so the fractional
    /// part `y = x · 2/π − 1` cancels 33 to 34 digits and the
    /// surviving-digit claim is exercised at full depth.
    #[test]
    fn reduce_wide_survives_deep_cancellation() {
        use crate::mock_format::ValueFmt128;

        // round_34(π/2) = 1.570796326794896619231321691639751 (34 digits).
        let x = ValueFmt128 {
            coef: 1_570_796_326_794_896_619_231_321_691_639_751,
            exp: -33,
            sign: false,
        };
        let (k2, r2, _) = reduce_wide::<ValueFmt128>(x);
        assert_eq!(k2, 1, "x is adjacent to 1 · π/2");
        // True residual: x − π/2 ≈ −4.42e-34 (x truncates π/2, whose
        // 35th digit is 4). The wide pipeline must see the residual's
        // magnitude decade (−34) and carry ≥ 100 digits of coefficient.
        assert!(r2.sign, "residual sign: x < π/2");
        let r_adj = r2.exp + r2.coef.decimal_digit_count() as i32 - 1;
        assert_eq!(r_adj, -34, "residual decade");
        assert!(
            r2.coef.decimal_digit_count() >= 100,
            "wide residual carries ≥ 100 significant digits, got {}",
            r2.coef.decimal_digit_count()
        );
        // And rung 1 agrees on the leading digits (its own fidelity
        // floor at maximum cancellation is ~43 digits).
        let (k1, r1, _) = reduce_body::<ValueFmt128, Extended>(Extended::ZERO, x);
        assert_eq!(k1, 1);
        let d = Extended2::from_extended(r1).sub(r2);
        if !d.is_zero() {
            let d_adj = d.exp + d.coef.decimal_digit_count() as i32 - 1;
            // Same 10^-36-relative floor as the sweep above (rung 1's
            // 38-digit π/2 truncation binds), on a residual of decade
            // −34.
            assert!(
                d_adj <= -34 - 36,
                "deep-cancellation agreement to 36 digits, divergence decade {d_adj}"
            );
        }
    }

    // -----------------------------------------------------------------
    // The unbounded rung (M8b, fd-4zo.17).

    #[cfg(feature = "unbounded-ladder")]
    mod dyn_rung {
        use super::*;
        use crate::extended_dyn::{DynArena, ExtendedDyn};
        use crate::mock_format::ValueFmt128;
        use ferrodec_multiword::{bigconst, DecBig};

        /// The coefficient of a dynamic value, read back through its
        /// `Debug` rendering.
        ///
        /// The arena *is* the width, so two runs at different
        /// precisions necessarily live in different arenas and no
        /// in-crate operation composes them. `Debug` prints the
        /// coefficient's decimal digits (`DecBig`'s `Display`), which
        /// makes it the one cross-arena readout the type exposes;
        /// re-interning those digits in the target arena is how the
        /// doubling test compares a `p = 440` residual against a
        /// `p = 220` one. Test-only, and deliberately not a production
        /// accessor.
        fn dyn_coef(v: ExtendedDyn<'_>) -> DecBig {
            let rendered = alloc::format!("{v:?}");
            let body = rendered
                .split("coef: ")
                .nth(1)
                .expect("ExtendedDyn's Debug renders a `coef:` field");
            let digits: alloc::vec::Vec<u8> = body
                .bytes()
                .take_while(u8::is_ascii_digit)
                .collect::<alloc::vec::Vec<u8>>();
            DecBig::from_ascii_digits(&digits)
        }

        /// Re-intern a dynamic value in another arena, rounded to that
        /// arena's width.
        fn rehome<'a>(a: &'a DynArena, v: ExtendedDyn<'_>) -> ExtendedDyn<'a> {
            a.exemplar()
                .from_decbig_with_sticky(dyn_coef(v), v.exponent(), v.sign(), false)
        }

        /// `U384` → `DecBig`, test-only: the differential needs fixed
        /// rung values on the growable substrate and nothing in
        /// production does.
        fn u384_as_decbig(c: U384) -> DecBig {
            let mut digits = alloc::vec::Vec::new();
            let mut cur = c;
            while !cur.is_zero() {
                let (q, d) = cur.div_rem10();
                digits.push(b'0' + d as u8);
                cur = q;
            }
            digits.reverse();
            DecBig::from_ascii_digits(&digits)
        }

        /// An [`Extended2`] as a dynamic value in `a`. Rung 2 keeps its
        /// coefficient inside 110 digits, so at any arena width from
        /// the 110-digit floor up this is exact.
        fn ext2_as_dyn(a: &DynArena, v: Extended2) -> ExtendedDyn<'_> {
            a.exemplar()
                .from_decbig_with_sticky(u384_as_decbig(v.coef), v.exp, v.sign, false)
        }

        /// Decade of a dynamic value (`exp + digits − 1`).
        fn adj(v: ExtendedDyn<'_>) -> i32 {
            v.exponent() + v.digit_count() as i32 - 1
        }

        /// Assert `|got − want| ≤ 10^(decade(want) + decades)`, both
        /// operands in the same arena. Exact agreement always passes.
        fn assert_agrees(
            got: ExtendedDyn<'_>,
            want: ExtendedDyn<'_>,
            decades: i32,
            label: &str,
        ) -> i32 {
            let d = got.sub(want).abs();
            if d.is_zero() {
                return i32::MIN;
            }
            assert!(
                !want.is_zero(),
                "{label}: reference is zero but the difference is not"
            );
            let rel = adj(d) - adj(want);
            assert!(
                rel <= decades,
                "{label}: divergence at relative decade {rel} (bound {decades}); \
                 got {got:?}, want {want:?}"
            );
            rel
        }

        /// Gate 1: the runtime generator indexes `2/π` the way the
        /// static table does.
        ///
        /// `two_over_pi_digits(n)` returns the first `n` *significant*
        /// digits; `two_over_pi_digit(i)` returns the `i`-th
        /// *fractional* digit. `2/π = 0.6366…` has a nonzero first
        /// fractional digit, so the two indexings coincide — and the
        /// windowed reduction reads the generator with exactly the
        /// index arithmetic it inherited from the table. Checking the
        /// deep tail of three runs is what pins that: a scale slip of
        /// one lands every compared digit wrong.
        ///
        /// The generator's documented bound is ≤ 1 unit of its last
        /// digit, so digit `n` is the one entitled to differ.
        /// Observed: exact agreement at all three depths, tail digit
        /// included.
        #[test]
        fn two_over_pi_generator_indexes_like_the_table() {
            let mut compared = 0u32;
            for n in [50u64, 500, 6300] {
                let d = bigconst::two_over_pi_digits(n);
                assert_eq!(d.decimal_digit_count(), n, "{n}-digit run digit count");
                for i in (n - 9)..=n {
                    let got = d.div_rem_pow10((n - i) as u32).0.div_rem10().1 as u8;
                    let want = two_over_pi_digit(i as usize);
                    assert_eq!(got, want, "digit {i} of the {n}-digit run");
                    compared += 1;
                }
            }
            assert_eq!(compared, 30, "three runs, ten tail digits each");
        }

        /// The dynamic widths reproduce the rung 2 constants at
        /// `p = 110`, which is the whole mirror claim in one assert.
        #[test]
        fn dyn_widths_reproduce_rung2_at_110() {
            assert_eq!(frac_digits_dyn(110), FRAC2_DIGITS);
            assert_eq!(i_hi_offset_dyn(110), I_HI_OFFSET2);
            assert_eq!(i_hi_offset_dyn(110), 110 + 70);
            // …and the π/2 coefficient is the rung 2 literal, digit for
            // digit. The literal is a *truncation* to 115 digits, and
            // the generated value is `floor((π/2) · 10^114)` within 2
            // units, so the assertion is equality up to that bound.
            // Observed: byte-identical.
            let generated = pi_over_two_coef_dyn(110);
            assert_eq!(
                generated.decimal_digit_count(),
                115,
                "p + 5 digits at p = 110"
            );
            let literal = u384_as_decbig(PI_OVER_TWO_COEF2);
            let diff = if generated.cmp_ref(&literal) == core::cmp::Ordering::Less {
                literal.sub(&generated)
            } else {
                generated.sub(&literal)
            };
            assert!(
                diff.to_u128().expect("a small difference fits u128") <= 2,
                "generated π/2 differs from the rung 2 literal by {diff}"
            );
        }

        /// Gate 2: the load-bearing differential. At `p = 110` the
        /// dynamic pipeline and `reduce_wide` are the same algorithm at
        /// the same widths on different substrates, so rung 2 is a
        /// term-for-term oracle over the full M6 grid.
        ///
        /// Bound derivation. The two runs differ in exactly three
        /// places:
        ///
        /// * the `2/π` window. Both truncate at the same `i_hi`, so the
        ///   tail truncation is common and cancels; only the
        ///   generator's ≤ 1 unit at digit `i_hi` remains, worth
        ///   ≤ `c · 10^(q − i_hi)` ≤ 10^-146 *absolute* in `x · 2/π` at
        ///   `p = 110`, hence ≤ 10^-146 · (π/2) absolute in `r`;
        /// * the `π/2` constant. The rung 2 literal is a truncation to
        ///   115 digits and the generated one lands within 2 units of
        ///   the same floor, so they agree to ≤ 1.3 · 10^-114 relative;
        /// * the final rounding. Both round half-even at 110
        ///   significant digits, from products that agree to the two
        ///   terms above; when those products straddle a rounding
        ///   boundary the delivered coefficients differ by one unit in
        ///   the 110th digit, i.e. 10^-109 relative.
        ///
        /// The third term dominates at 10^-109, and the first is below
        /// 10^-109 relative for any residual down to decade −37 (the
        /// M6 sibling test's own 10^-36 agreement floor already bounds
        /// this grid's residuals well above that). **10^-105** is
        /// therefore a bound with four orders of margin that still
        /// fails loudly on a genuine width, index or scale bug — all of
        /// which move the leading digits, not the 110th.
        ///
        /// Observed on this grid: byte-identical residuals on every one
        /// of the 60 pairs — the expected outcome, since the generated
        /// `2/π` digits equal the table's and the generated π/2 equals
        /// the rung 2 literal exactly (both pinned by the two tests
        /// above), so the two pipelines run identical integers through
        /// identical clauses. The asserted envelope is what protects
        /// the test from a future generator whose last digit moves.
        #[test]
        fn reduce_dyn_agrees_with_reduce_wide() {
            let coefs: [u128; 5] = [
                1,
                3_141_592_653_589_793_238_462_643_383_279_503,
                9_999_999_999_999_999_999_999_999_999_999_999,
                2_718_281_828_459_045_235_360_287_471_352_662,
                7_071_067_811_865_475_244_008_443_621_048_490,
            ];
            let exps: [i32; 12] = [-40, -33, -30, -10, -1, 0, 5, 50, 500, 3000, 6000, 6077];

            let a = DynArena::new(110);
            let ex = a.exemplar();
            let mut checked = 0u32;
            for &coef in &coefs {
                for &exp in &exps {
                    let x = ValueFmt128 {
                        coef,
                        exp,
                        sign: false,
                    };
                    let (k2, r2, s2) = reduce_wide::<ValueFmt128>(x);
                    let (kd, rd, sd) = reduce_dyn::<ValueFmt128>(ex, x);
                    assert_eq!(k2, kd, "quadrant split for coef={coef} exp={exp}");
                    assert_eq!(s2, sd, "status for coef={coef} exp={exp}");
                    assert_agrees(
                        rd,
                        ext2_as_dyn(&a, r2),
                        -105,
                        &alloc::format!("residual for coef={coef} exp={exp}"),
                    );
                    checked += 1;
                }
            }
            assert_eq!(checked, 60, "every pair exercised");
        }

        /// Gate 3: the deep-cancellation witness, the dynamic sibling
        /// of `reduce_wide_survives_deep_cancellation`. The 34-digit
        /// truncation of π/2 is the deepest input the format admits:
        /// `x − π/2 ≈ −4.4 · 10^-34`, so `y = x · 2/π − 1` cancels 33
        /// to 34 digits and the surviving-precision claim is exercised
        /// at full depth.
        ///
        /// Agreement bound against rung 2. The dynamic run at `p = 220`
        /// carries its own π/2 truncation (< 10^-223 relative) and one
        /// 220-digit rounding (10^-219), both negligible here; the
        /// binding term is rung 2's own delivery, which rounds to 110
        /// significant digits and so carries up to one unit in the
        /// 110th digit, 10^-109 relative, on top of its < 10^-114
        /// truncations. **10^-108** is that floor with an order of
        /// margin. Observed: agreement at relative decade −109 exactly
        /// — one unit in rung 2's 110th digit, the predicted binding
        /// term and nothing above it. The margin here is one decimal
        /// order rather than the sweep's four, because at maximum
        /// cancellation rung 2 delivers its narrowest residual and the
        /// comparison measures that width directly.
        #[test]
        fn reduce_dyn_survives_deep_cancellation() {
            const P: u32 = 220;
            // round_34(π/2) = 1.570796326794896619231321691639751.
            let x = ValueFmt128 {
                coef: 1_570_796_326_794_896_619_231_321_691_639_751,
                exp: -33,
                sign: false,
            };

            let a = DynArena::new(P);
            let ex = a.exemplar();
            let (k, r, status) = reduce_dyn::<ValueFmt128>(ex, x);
            assert_eq!(k, 1, "x is adjacent to 1 · π/2");
            assert_eq!(status, Status::INEXACT);
            assert!(r.sign(), "residual sign: x < π/2");
            assert_eq!(adj(r), -34, "residual decade");
            assert!(
                r.digit_count() >= P - 5,
                "the dynamic residual carries ≥ {} significant digits, got {}",
                P - 5,
                r.digit_count()
            );

            let (k2, r2, _) = reduce_wide::<ValueFmt128>(x);
            assert_eq!(k2, 1);
            assert_agrees(r, ext2_as_dyn(&a, r2), -108, "deep-cancellation residual");
        }

        /// Gate 4: self-consistency across the Ziv doubling. A rung
        /// that answers differently at 220 and 440 digits cannot be a
        /// refinement of itself, and every width in the pipeline moves
        /// between the two runs (window depth, fractional width, both
        /// constants' depths).
        ///
        /// Bound derivation. The `p = 220` residual is delivered
        /// rounded to 220 significant digits, so it carries up to one
        /// unit in the 220th digit — 10^-219 relative — against the
        /// `p = 440` run, whose own error is 220 orders further down.
        /// Re-interning the wide residual in the 220-digit arena adds
        /// one more such rounding. **10^-215** is that floor with four
        /// orders of margin. Observed worst case on this grid:
        /// byte-identical.
        #[test]
        fn reduce_dyn_is_stable_across_the_doubling() {
            let coefs: [u128; 2] = [
                3_141_592_653_589_793_238_462_643_383_279_503,
                9_999_999_999_999_999_999_999_999_999_999_999,
            ];
            let exps: [i32; 5] = [-1, 0, 50, 3000, 6077];

            let narrow = DynArena::new(220);
            let wide = DynArena::new(440);
            let mut checked = 0u32;
            for &coef in &coefs {
                for &exp in &exps {
                    let x = ValueFmt128 {
                        coef,
                        exp,
                        sign: false,
                    };
                    let (k_n, r_n, s_n) = reduce_dyn::<ValueFmt128>(narrow.exemplar(), x);
                    let (k_w, r_w, s_w) = reduce_dyn::<ValueFmt128>(wide.exemplar(), x);
                    assert_eq!(k_n, k_w, "quadrant for coef={coef} exp={exp}");
                    assert_eq!(s_n, s_w, "status for coef={coef} exp={exp}");
                    assert_agrees(
                        r_n,
                        rehome(&narrow, r_w),
                        -215,
                        &alloc::format!("doubling residual for coef={coef} exp={exp}"),
                    );
                    checked += 1;
                }
            }
            assert_eq!(checked, 10, "every pair exercised");
        }

        /// Gate 5: the high-exponent smoke test. `q_max` for a
        /// normalised Decimal128 coefficient is +6111, so
        /// `coef = 10^34 − 1` at `exp = 6077` sits at the top of the
        /// representable range and drives the deepest window the
        /// generator is ever asked for (`i_hi = 6077 + 290 = 6367` at
        /// `p = 220`).
        #[test]
        fn reduce_dyn_handles_the_high_exponent_corner() {
            let a = DynArena::new(220);
            let ex = a.exemplar();
            let x = ValueFmt128 {
                coef: 9_999_999_999_999_999_999_999_999_999_999_999,
                exp: 6077,
                sign: false,
            };
            let (k, r, status) = reduce_dyn::<ValueFmt128>(ex, x);
            assert!(k < 4, "quadrant index in range, got {k}");
            assert_eq!(status, Status::INEXACT);
            // |r| ≤ π/4 (loose bound; the contract's ±2 ULP overrun is
            // far below the slack in 0.7854).
            let quarter_pi_loose = ex.parse_str("0.7854");
            assert!(
                r.abs().cmp(quarter_pi_loose) != core::cmp::Ordering::Greater,
                "residual out of range: {r:?}"
            );
        }

        /// The seam itself: `ExtNum::reduce_trig` on the dynamic rung
        /// is `reduce_dyn`, so the ladder gets the runtime reduction
        /// rather than a rung 2 answer widened after the fact.
        #[test]
        fn reduce_trig_dispatches_to_reduce_dyn() {
            let a = DynArena::new(220);
            let ex = a.exemplar();
            let x = ValueFmt128 {
                coef: 2_718_281_828_459_045_235_360_287_471_352_662,
                exp: 50,
                sign: false,
            };
            let (k_seam, r_seam, s_seam) = ex.reduce_trig::<ValueFmt128>(x);
            let (k_direct, r_direct, s_direct) = reduce_dyn::<ValueFmt128>(ex, x);
            assert_eq!(k_seam, k_direct);
            assert_eq!(s_seam, s_direct);
            assert_eq!(
                r_seam.cmp(r_direct),
                core::cmp::Ordering::Equal,
                "the seam must deliver the same residual"
            );
        }
    }
}
