//! Moved from `ferrodec/src/math/argred.rs` @ commit 82a7fe1 (P0a.2 c7).
//! Behaviour-neutral: genericized over [`DecimalFormat`]; the
//! `Decimal128` instantiation is byte-identical to the pre-move kernel.
//!
//! Payne-Hanek argument reduction for `sin` / `cos`.
//!
//! ## Why
//!
//! The naive reduction `r = x − round(x / (π/2)) · (π/2)` works while
//! `|x|` is small enough that the cancellation in the subtraction
//! leaves at least 34 good digits. For `Decimal128`'s 34-digit
//! envelope that holds up to `|x| ≈ 10^9`; past that, more digits of
//! `π/2` get cancelled out than the native arithmetic carries, and
//! `r` rapidly loses meaning.
//!
//! ## Algorithm
//!
//! Payne and Hanek (1983, [doi:10.1145/29380.29384]) observed that the
//! cancellation is itself the reduction — multiplying `x` by an
//! extended-precision `2/π` and discarding the integer part gives the
//! reduced argument *without* any catastrophic subtraction. The product
//! only needs digits of `2/π` in a narrow window around the
//! integer / fraction boundary of `x · 2/π`, so storage scales linearly
//! with the input's exponent rather than exponentially with the loss
//! of precision.
//!
//! For `Decimal128` the maximum magnitude is `≈ 10^{6145}`, so we
//! embed `2/π` to 6 300 decimal digits (≈ 2.8 KB in flash, lives in
//! `.rodata`). Each call extracts a ~78-digit window indexed by the
//! input's unbiased exponent, multiplies by the 34-digit coefficient
//! into a `U384`, and reads the integer part `mod 4` and the leading
//! ~38 fractional digits directly out of the result. The fractional
//! part is then multiplied by an extended-precision `π/2` (80 digits,
//! also embedded) to yield `r` with 1-2 ULP of error against the true
//! reduction.
//!
//! ## Storage budget for the table
//!
//! The window we need is `d_{q-1} … d_{q + 77}`, where `q` is the
//! unbiased exponent (`biased_exp − BIAS`). With `q_max = +6111`
//! (largest representable unbiased exponent for a normalised
//! coefficient) we read up to `d_{6188}`, so 6 300 digits gives ~110
//! digits of headroom.
//!
//! ## Sign and rounding
//!
//! [`reduce`] takes an absolute value (sign separated by the caller)
//! and returns `k = round(|x| · 2/π) mod 4` plus the residual `r`,
//! where `|x| − k · π/2 = r` and `|r| ≤ π/4 + 2 · ULP(π/4)`. Callers
//! must adjust `k` and the residual sign for negative inputs (see
//! `sincos.rs`).

use crate::extended::Extended;
use crate::format::DecimalFormat;
use ferrodec_ieee::Status;
use ferrodec_ieee::{decimal_digit_count_u128 as decimal_digit_count, IeeeDecodedClass as Class};
use ferrodec_multiword::{u256::widening_mul_u128, U256, U384, U512};

mod table {
    // Auto-generated by tools/gen_argred.py — to regenerate run:
    //   nix-shell -p python3Packages.mpmath --run \
    //     'python3 tools/gen_argred.py' > /tmp/argred_consts.rs
    // and paste the body here.
    //
    // 2/π first 40 digits: 0.6366197723675813430755350534900574481378…

    pub(super) const TWO_OVER_PI_DIGITS: usize = 6300;
    pub(super) const TWO_OVER_PI: &[u32; 700] = &[
        636_619_772,
        367_581_343,
        75_535_053,
        490_057_448,
        137_838_582,
        961_825_794,
        990_669_376,
        235_587_190,
        536_906_140,
        360_455_211,
        65_012_343,
        824_291_370,
        907_031_832,
        147_571_647,
        384_458_314,
        611_511_869,
        642_926_799,
        356_916_959,
        867_749_636,
        310_292_310,
        985_587_701,
        230_754_869,
        571_584_869,
        590_646_773,
        449_560_966,
        894_516_047,
        329_520_456,
        890_799_022,
        863_761_847,
        560_347_610,
        695_824_481,
        957_643_747,
        751_376_342,
        114_892_399,
        785_773_600,
        994_689_390,
        957_838_443,
        593_292_387,
        132_299_624,
        667_945_851,
        218_797_794,
        608_751_526,
        299_146_267,
        856_964_155,
        983_496_557,
        394_439_935,
        472_396_799,
        849_771_502,
        340_684_715,
        433_724_470,
        75_068_642,
        186_190_147,
        952_038_957,
        841_459_037,
        335_072_237,
        209_977_986,
        541_221_308,
        627_102_012,
        881_299_111,
        265_588_664,
        91_786_992,
        478_392_663,
        362_424_067,
        212_143_992,
        535_647_949,
        995_331_146,
        617_741_119,
        20_280_064,
        962_710_257,
        555_398_285,
        243_520_488,
        797_504_590,
        725_511_058,
        951_562_532,
        272_185_831,
        913_927_045,
        249_709_256,
        279_843_100,
        98_001_191,
        39_428_356,
        227_611_187,
        140_526_100,
        840_065_270,
        984_083_699,
        246_424_962,
        245_824_812,
        585_936_356,
        993_836_765,
        740_846_301,
        630_224_803,
        486_106_427,
        208_868_636,
        563_029_898,
        330_890_390,
        985_141_599,
        500_621_317,
        563_255_927,
        89_637_433,
        19_188_293,
        314_876_162,
        799_903_630,
        630_831_397,
        388_157_435,
        931_234_869,
        370_256_146,
        758_046_650,
        182_823_773,
        310_525_074,
        600_104_490,
        871_884_612,
        845_039_801,
        754_671_780,
        150_502_243,
        345_268_467,
        810_390_325,
        128_997_664,
        933_372_580,
        424_494_147,
        514_252_454,
        546_768_668,
        568_278_987,
        840_517_002,
        313_344_212,
        478_434_378,
        39_358_226,
        874_839_818,
        986_041_726,
        495_262_070,
        323_357_771,
        919_883_998,
        21_017_550,
        264_517_783,
        533_227_384,
        203_141_166,
        60_564_161,
        957_195_402,
        555_264_310,
        478_797_229,
        364_155_998,
        314_767_562,
        392_374_951,
        88_247_501,
        728_908_757,
        205_465_021,
        44_955_121,
        550_155_524,
        427_256_270,
        617_363_313,
        114_107_733,
        707_198_224,
        283_161_544,
        241_410_955,
        984_980_503,
        982_997_105,
        188_094_376,
        382_337_204,
        659_318_564,
        742_310_849,
        623_017_797,
        828_087_159,
        79_169_637,
        961_309_179,
        80_866_598,
        414_261_272,
        614_176_015,
        362_759_498,
        870_766_355,
        52_763_866,
        27_857_619,
        107_882_750,
        734_627_112,
        419_119_181,
        801_413_583,
        33_207_527,
        354_751_751,
        64_499_259,
        812_239_862,
        320_876_334,
        395_004_140,
        508_516_172,
        926_321_994,
        878_747_511,
        37_862_653,
        848_841_368,
        177_634_219,
        914_015_170,
        954_777_174,
        146_477_511,
        317_149_437,
        513_738_812,
        920_948_583,
        351_694_228,
        474_545_367,
        717_840_732,
        729_167_856,
        660_035_132,
        317_325_413,
        991_163_989,
        834_597_161,
        69_802_439,
        574_756_378,
        353_220_134,
        812_215_221,
        892_492_863,
        237_727_907,
        41_291_325,
        256_759_238,
        999_289_753,
        340_697_427,
        959_390_004,
        158_002_735,
        520_159_146,
        894_398_432,
        96_010_956,
        43_499_819,
        419_151_694,
        273_044_559,
        795_613_075,
        989_708_333,
        984_459_683,
        315_615_107,
        138_972_142,
        18_273_824,
        334_685_917,
        233_826_893,
        308_141_941,
        570_224_808,
        347_357_296,
        398_248_847,
        13_273_576,
        83_883_174,
        283_099_861,
        995_234_744,
        265_443_874,
        647_868_149,
        898_168_411,
        324_877_007,
        384_899_339,
        964_644_598,
        266_224_151,
        878_704_559,
        725_131_984,
        310_433_111,
        960_403_132,
        144_009_353,
        91_951_634,
        160_955_046,
        229_781_723,
        704_047_640,
        217_351_993,
        556_186_196,
        849_931_806,
        428_291_412,
        20_908_840,
        944_070_093,
        252_692_719,
        37_244_201,
        312_620_437,
        495_654_558,
        581_223_170,
        428_720_334,
        471_819_506,
        898_583_921,
        895_909_169,
        792_436_803,
        748_503_147,
        673_331_583,
        545_135_961,
        743_474_666,
        559_026_937,
        805_638_014,
        549_308_766,
        972_455_522,
        655_322_903,
        692_110_389,
        380_242_192,
        851_112_148,
        261_351_132,
        128_683_950,
        939_866_273,
        963_201_307,
        954_026_967,
        165_858_734,
        33_126_467,
        413_257_344,
        642_923_980,
        599_412_479,
        278_935_033,
        776_839_366,
        623_816_609,
        2_573_577,
        251_457_761,
        535_534_246,
        35_190_865,
        800_682_588,
        270_075_098,
        242_366_434,
        867_431_431,
        756_904_939,
        25_326_844,
        531_994_623,
        766_387_562,
        879_402_754,
        976_920_230,
        76_790_822,
        760_152_873,
        570_248_813,
        549_694_145,
        27_233_416,
        626_069_188,
        435_246_887,
        183_747_330,
        259_540_749,
        998_994_834,
        212_466_393,
        224_405_568,
        578_178_406,
        459_538_110,
        810_045_644,
        280_994_086,
        958_980_415,
        466_945_615,
        491_440_398,
        699_572_694,
        247_248_284,
        696_191_559,
        747_554_622,
        769_231_394,
        9_222_822,
        857_625_455,
        452_809_474,
        80_429_640,
        229_943_691,
        244_628_878,
        720_159_129,
        903_812_006,
        678_340_884,
        921_385_675,
        94_601_741,
        870_585_826,
        263_887_604,
        492_339_068,
        397_238_834,
        365_134_586,
        676_767_107,
        755_165_733,
        262_266_026,
        792_528_656,
        608_403_582,
        846_914_495,
        370_428_271,
        380_704_044,
        538_032_027,
        979_073_689,
        427_958_499,
        522_063_103,
        923_813_588,
        323_419_002,
        390_145_062,
        596_137_577,
        816_823_271,
        545_742_732,
        168_001_260,
        382_378_973,
        757_010_179,
        402_699_657,
        163_459_005,
        769_213_285,
        329_827_804,
        653_978_271,
        15_757_696,
        144_362_175,
        334_211_316,
        973_688_139,
        793_746_460,
        586_529_144,
        99_106_666,
        419_812_562,
        629_374_302,
        120_563_633,
        119_523_659,
        146_773_739,
        690_950_410,
        539_991_319,
        828_072_647,
        857_284_932,
        561_903_051,
        589_936_331,
        564_696_389,
        913_055_159,
        672_679_975,
        794_999_086,
        79_592_749,
        66_517_840,
        732_215_833,
        310_083_694,
        540_274_155,
        569_138_729,
        890_398_901,
        132_030_674,
        277_503_346,
        388_916_792,
        977_189_896,
        246_552_732,
        455_833_226,
        977_394_067,
        714_389_532,
        949_570_649,
        609_738_007,
        991_239_761,
        608_758_453,
        933_709_445,
        470_579_965,
        530_861_666,
        425_369_931,
        745_496_740,
        244_904_434,
        452_847_994,
        533_851_388,
        397_673_597,
        709_718_236,
        625_133_359,
        619_215_284,
        700_046_448,
        466_688_207,
        650_317_214,
        211_716_964,
        537_612_464,
        536_449_981,
        273_543_707,
        833_961_775,
        387_231_396,
        389_593_123,
        542_118_818,
        61_221_596,
        560_395_479,
        536_353_461,
        934_660_889,
        867_449_634,
        901_605_616,
        36_471_496,
        848_818_092,
        301_338_958,
        901_525_976,
        155_367_623,
        473_692_463,
        785_290_977,
        356_264_500,
        649_572_425,
        132_781_295,
        533_568_526,
        138_225_526,
        47_008_140,
        434_983_823,
        280_449_501,
        743_907_262,
        136_074_962,
        957_736_145,
        359_121_552,
        688_401_812,
        676_731_807,
        795_183_670,
        695_816_711,
        516_974_110,
        469_628_984,
        237_566_410,
        929_131_517,
        872_774_596,
        515_798_859,
        813_730_210,
        894_366_637,
        192_289_919,
        943_224_507,
        602_932_875,
        378_107_177,
        340_182_320,
        780_997_026,
        522_481_950,
        646_453_746,
        135_968_115,
        18_083_422,
        137_657_639,
        620_519_309,
        98_186_364,
        725_288_931,
        362_046_664,
        626_028_393,
        502_297_349,
        181_945_248,
        164_486_865,
        523_662_424,
        644_662_928,
        333_224,
        458_424_725,
        121_305_034,
        783_806_409,
        852_866_455,
        430_645_921,
        887_973_083,
        108_526_576,
        480_637_984,
        44_253_132,
        208_303_833,
        394_012_203,
        163_823_399,
        319_287_469,
        611_593_542,
        55_329_582,
        808_323_055,
        902_017_169,
        39_390_588,
        284_065_707,
        897_538_017,
        236_663_458,
        113_441_299,
        734_417_418,
        628_950_231,
        664_546_529,
        648_183_123,
        987_886_265,
        360_886_352,
        218_317_725,
        313_112_022,
        98_452_835,
        560_749_684,
        843_697_956,
        416_402_086,
        198_723_884,
        548_830_160,
        228_438_536,
        265_725_429,
        817_596_639,
        77_743_155,
        683_173_702,
        471_132_088,
        948_045_945,
        699_700_956,
        994_914_852,
        528_087_066,
        944_302_658,
        239_309_043,
        829_662_640,
        937_514_974,
        516_528_438,
        994_358_860,
        285_229_564,
        162_905_741,
        656_718_822,
        889_061_919,
        215_260_510,
        383_164_960,
        101_378_721,
        928_810_469,
        369_196_004,
        81_932_249,
        852_135_185,
        898_712_762,
        7_247_321,
        500_615_211,
        518_093_733,
        678_200_854,
        275_908_365,
        162_245_727,
        151_516_834,
        482_297_999,
        703_159_027,
        607_396_841,
        296_825_885,
        540_764_555,
        259_025_608,
        390_422_195,
        831_751_405,
        656_165_812,
        206_063_358,
        571_293_061,
        624_082_413,
        247_566_346,
        281_088_345,
        1_079_665,
        575_006_111,
        549_442_432,
        458_227_793,
        684_128_963,
        109_090_968,
        660_545_693,
        746_797_086,
        536_123_762,
        122_992_261,
        74_037_206,
        635_685_476,
        856_572_517,
        485_364_246,
        286_148_562,
        481_591_390,
        473_706_011,
        912_314_425,
        67_879_843,
        236_736_893,
        905_340_190,
        986_876_069,
        801_805_784,
        665_531_384,
        832_963_469,
        438_040_948,
        521_161_777,
        511_763_414,
        13_781_770,
        533_652_250,
        522_983_805,
        532_124_091,
        725_877_378,
        673_314_070,
        653_129_660,
        608_407_176,
        905_775_828,
        724_868_680,
        870_259_687,
        857_797_586,
        128_888_750,
        633_952_978,
        47_637_605,
        362_017_728,
        559_434_514,
        484_332_717,
        575_843_377,
        559_207_659,
        149_559_089,
        324_114_524,
        52_594_782,
        85_048_207,
        311_225_397,
        828_474_651,
        113_026_395,
        324_021_406,
        209_266_639,
        375_763_608,
        872_252_578,
        180_848_519,
        158_937_885,
        954_965_033,
        72_895_440,
        944_108_439,
        924_766_082,
        275_293_889,
        593_432_053,
        464_273_514,
        531_547_171,
        447_892_946,
        901_442_674,
        86_742_528,
        47_795_912,
        293_583_367,
        676_266_383,
        354_714_117,
        649_674_872,
        869_119_500,
        244_157_842,
        592_783_429,
        824_802_435,
        684_913_665,
        577_495_386,
        198_359_728,
        113_924_945,
        733_864_478,
        829_297_238,
        183_436_293,
        447_514_516,
        252_740_066,
        42_507_030,
        740_486_543,
        35_478_522,
        980_799_688,
        4_310_670,
        732_378_792,
        599_024_907,
        297_391_746,
        852_433_648,
        408_780_835,
        979_276_497,
        761_950_046,
        842_367_376,
        559_631_557,
        823_100_738,
        486_476_166,
        123_738_175,
        211_235_754,
        512_292_950,
        314_461_071,
        188_457_329,
        296_787_943,
        122_255_052,
        72_353_754,
        656_242_870,
        147_328_545,
        51_868_489,
        704_377_141,
        604_438_528,
        730_510_604,
        804_680_902,
        117_171_586,
    ];

    /// Reference value used to derive [`super::PI_OVER_TWO_COEF_38`].
    /// Kept here so the regenerator script can dump both the table and
    /// this string in one go, and so a unit test can pin the coefficient
    /// constant against it.
    #[allow(dead_code)]
    pub(super) const PI_OVER_TWO_STR: &str =
        "1.5707963267948966192313216916397514420985846996875529104874722961539082031431044";
}

// ----------------------------------------------------------------------------
// Algorithm constants. See module-level docs for derivation.

/// Fractional decimal digits we extract from the windowed product.
///
/// Sized to absorb up to 33 leading zeros (or 9s after rounding) in
/// the fractional residual when the input is within 1 ULP of an
/// integer multiple of π/2. The guaranteed surviving precision is
/// `FRAC_DIGITS − 33 = 43` significant digits in `y_signed`. That
/// is below `EXT_PRECISION = 50` of the downstream `Extended`
/// envelope, but comfortably above Decimal128's 34-digit boundary
/// (the relevant margin for callers): `43 − 34 = 9` headroom digits
/// at the worst case.
///
/// The 2026-05-10 six-agent review flagged the 9-digit margin as
/// "tight". Investigation during Slice E found the current budget
/// is empirically sufficient (the `property_sincos_large` suite
/// passes at 1 ULP across magnitudes through 1e500), so no bump
/// landed in 1.15. Bumping `FRAC_DIGITS` past 77 requires switching
/// the windowed product machinery from U256 to U384 (10^78 exceeds
/// U256's ~1.16 × 10^77 capacity); the refactor is well-supported
/// by the existing `u384_mul_u128_to_u512` helper but is deferred
/// until a failing high-magnitude case surfaces.
const FRAC_DIGITS: u32 = 76;
/// Extra digits below the precision window to absorb truncation
/// carries from the unread tail of `2/π`.
const CARRY_GUARD: u32 = 4;
/// Combined offset added to `q` to compute the high end of the window
/// (so that `i_hi = q + I_HI_OFFSET`).
const I_HI_OFFSET: u32 = FRAC_DIGITS + 33 + CARRY_GUARD; // = 113

/// 38 leading decimal digits of π/2, parsed as a u128 (truncated, not
/// rounded — pinned to [`table::PI_OVER_TWO_STR`] by
/// `pi_over_two_coef_matches_string`). Multiplied by the extracted
/// fractional residual (also up to 38 digits) to produce
/// `r = y · π/2` to ~75 digits before final rounding to 34. The
/// truncation introduces ≤ 10^{-37} relative error in π/2, which
/// after multiplying by `|y| ≤ 0.5` and rounding `r` to 34 digits
/// contributes ≤ 10^{-3} ULP — negligible.
const PI_OVER_TWO_COEF_38: u128 = 15_707_963_267_948_966_192_313_216_916_397_514_420;
const PI_OVER_TWO_EXP_38: i32 = -37;

// ----------------------------------------------------------------------------
// Table accessors.

/// Decimal digit `i` of `2/π` (1-indexed; `i = 1` is the `6` in
/// `0.636…`). Returns `0` for indices beyond the table — callers must
/// pre-clip.
#[inline]
fn two_over_pi_digit(i: usize) -> u8 {
    debug_assert!((1..=table::TWO_OVER_PI_DIGITS).contains(&i));
    let idx = i - 1;
    let limb = table::TWO_OVER_PI[idx / 9];
    // Position 0 in a limb is the MSD (10^8), position 8 is the LSD.
    let pos = idx % 9;
    let shift = 10u32.pow(8 - pos as u32);
    ((limb / shift) % 10) as u8
}

// ----------------------------------------------------------------------------
// Multi-word multiplications used by the Payne-Hanek pipeline.

/// `a × b` for a `U384` and a `u128`, producing the **full** product
/// in a `U512`. Used by the windowed-product step where `a` is a
/// `2/π` window (up to ~115 decimal digits) and `b` is a 34-digit
/// Decimal128 coefficient — the product can grow up to ~149 digits,
/// which exceeds `U384`'s ~115-digit envelope.
#[inline]
fn u384_mul_u128_to_u512(a: U384, b: u128) -> U512 {
    // `widening_mul_u128` returns `(hi, lo)`.
    let (l_hi, l_lo) = widening_mul_u128(a.lo, b);
    let (m_hi, m_lo) = widening_mul_u128(a.mid, b);
    let (h_hi, h_lo) = widening_mul_u128(a.hi, b);

    // Layout in U512 (4 × u128 limbs lo / mid_lo / mid_hi / hi):
    //   lo     bits 0..127:    l_lo
    //   mid_lo bits 128..255:  l_hi + m_lo  (with carry into mid_hi)
    //   mid_hi bits 256..383:  m_hi + h_lo  (with carry from below + into hi)
    //   hi     bits 384..511:  h_hi (+ carry from below)
    let lo = l_lo;
    let (mid_lo, c1) = l_hi.overflowing_add(m_lo);
    let (mh_a, c2) = m_hi.overflowing_add(h_lo);
    let (mid_hi, c2b) = mh_a.overflowing_add(u128::from(c1));
    let hi = h_hi
        .wrapping_add(u128::from(c2))
        .wrapping_add(u128::from(c2b));

    U512 {
        lo,
        mid_lo,
        mid_hi,
        hi,
    }
}

/// `a × b` for a `U256` and a `u128`, producing the full product in a
/// `U384`. Used by `make_residual` to multiply the (up to 76-digit)
/// fractional magnitude by the 38-digit π/2 coefficient.
#[inline]
fn u256_mul_u128_to_u384(a: U256, b: u128) -> U384 {
    let (l_hi, l_lo) = widening_mul_u128(a.lo, b);
    let (h_hi, h_lo) = widening_mul_u128(a.hi, b);
    // Layout: lo = l_lo; mid = l_hi + h_lo; hi = h_hi + carry.
    let lo = l_lo;
    let (mid, c1) = l_hi.overflowing_add(h_lo);
    let hi = h_hi.wrapping_add(u128::from(c1));
    U384 { lo, mid, hi }
}

// ----------------------------------------------------------------------------
// Window extraction.

/// Build the integer `W = sum_{i=i_lo}^{i_hi} d_i · 10^{i_hi − i}`
/// where `d_i` is the i-th decimal digit of `2/π` (1-indexed).
fn extract_window(i_lo: usize, i_hi: usize) -> U384 {
    debug_assert!(i_lo >= 1 && i_hi <= table::TWO_OVER_PI_DIGITS && i_lo <= i_hi);
    let mut w = U384::ZERO;
    for i in i_lo..=i_hi {
        w = w.mul10();
        w = w.add(U384::from_u128(u128::from(two_over_pi_digit(i))));
    }
    w
}

// ----------------------------------------------------------------------------
// Splitting the windowed product into integer mod 4 and fractional part.

/// Result of the windowed multiplication, split into (integer mod 100,
/// fractional digits with high-order digit first, length).
struct Split {
    /// `floor(x · 2/π) mod 100`. Two decimal digits.
    floor_mod_100: u32,
    /// Decimal digits of the fractional part, MSD first. Length =
    /// `FRAC_DIGITS as usize`. Digit[0] is the 10^{-1} place; the
    /// last digit is the 10^{-FRAC_DIGITS} place.
    frac_digits: [u8; FRAC_DIGITS as usize],
}

/// Given `p = c · W` (a `U512`) and the implicit scale
/// `10^{-I_HI_OFFSET}`, peel off the digits that matter:
///   * positions `0 .. (I_HI_OFFSET − FRAC_DIGITS)` are the unread tail
///     (low-order noise + carry guard) — discarded.
///   * positions `(I_HI_OFFSET − FRAC_DIGITS) .. I_HI_OFFSET` are the
///     `FRAC_DIGITS` leading fractional digits (LSD first internally,
///     stored MSD-first in `frac_digits`).
///   * positions `I_HI_OFFSET .. I_HI_OFFSET + 2` are the integer mod 100.
fn split_product(mut p: U512) -> Split {
    let mut frac = [0u8; FRAC_DIGITS as usize];

    // Drop the unread tail. With FRAC_DIGITS = 76 and I_HI_OFFSET =
    // 113, that's 37 digits of low-order tail (33 from the
    // c-coefficient overlap below the fractional window, plus
    // CARRY_GUARD = 4).
    let drop = I_HI_OFFSET - FRAC_DIGITS;
    for _ in 0..drop {
        let (q, _) = p.div_rem10();
        p = q;
    }

    // Read the FRAC_DIGITS fractional digits (LSD first, then reverse).
    for slot in frac.iter_mut().rev() {
        let (q, d) = p.div_rem10();
        *slot = d as u8;
        p = q;
    }

    // Next 2 digits are the integer mod 100.
    let (q, d0) = p.div_rem10();
    let (_, d1) = q.div_rem10();
    let floor_mod_100 = d0 + d1 * 10;

    Split {
        floor_mod_100,
        frac_digits: frac,
    }
}

// ----------------------------------------------------------------------------
// Reconstruct the residual `r = y · π/2` as a `Decimal128`.

/// Build an `Extended` for `sign · y · π/2`, where `y` is given as the
/// fractional digit array with implicit scale `10^{-FRAC_DIGITS}`,
/// optionally minus `1` (when the rounding step chose to round up,
/// leaving a negative residual).
///
/// All `FRAC_DIGITS` digits of `y` are preserved into the windowed
/// product `y · π/2_38`, which then collapses to `Extended`'s
/// 50-digit envelope via `shift_right_to_u256`. The post-cancellation
/// effective precision in `y_mag` is at least 43 digits (76 − 33
/// leading zeros worst case), more than enough to round `r` faithfully.
fn make_residual(
    frac_digits: [u8; FRAC_DIGITS as usize],
    rounded_up: bool,
    sign: bool,
) -> Extended {
    // Pack all FRAC_DIGITS fractional digits into a U256. 76 digits ≈
    // 252 bits — fits comfortably (U256 holds up to 10^77).
    let mut y_coef = U256::ZERO;
    for &d in &frac_digits {
        y_coef = y_coef.mul10().add(U256::from_u128(u128::from(d)));
    }

    // For `round_up`: y_signed = (y_coef · 10^{-FRAC_DIGITS}) − 1, so
    // y_mag = 10^FRAC_DIGITS − y_coef. Build 10^FRAC_DIGITS in U256.
    let one_scaled = pow10_u256(FRAC_DIGITS);
    let mut y_signed_neg = false;
    let y_mag: U256 = if rounded_up {
        y_signed_neg = true;
        one_scaled.sub(y_coef)
    } else {
        y_coef
    };

    if y_mag.is_zero() {
        return Extended::ZERO;
    }

    let net_sign = sign ^ y_signed_neg;

    // y_mag (≤ 76 digits) · PI_OVER_TWO_COEF_38 (38 digits) → U384
    // (up to 114 digits ≈ 378 bits, well inside U384's 384-bit cap).
    let coef = u256_mul_u128_to_u384(y_mag, PI_OVER_TWO_COEF_38);

    // Collapse U384 down to the U256 / Extended envelope, accumulating
    // dropped digits into a sticky bit so round-half-even can act on it.
    let (coef_u256, shift, sticky) = coef.shift_right_to_u256(false);

    // Combined exponent: y is at scale 10^{-FRAC_DIGITS}, π/2 at
    // 10^{PI_OVER_TWO_EXP_38} = 10^{-37}, plus the shift introduced by
    // the U384 → U256 collapse.
    let exp = -(FRAC_DIGITS as i32) + PI_OVER_TWO_EXP_38 + shift as i32;
    Extended::from_components_with_sticky(coef_u256, exp, net_sign, sticky)
}

/// `10^k` as a `U256`. Bounded loop; caller keeps `k` ≤ 76 for the
/// `U256` envelope.
fn pow10_u256(k: u32) -> U256 {
    debug_assert!(k <= 76, "pow10_u256: k > 76 overflows U256");
    let mut v = U256::from_u128(1);
    let mut i = 0;
    while i < k {
        v = v.mul10();
        i += 1;
    }
    v
}

// ----------------------------------------------------------------------------
// Public entry point.

/// Reduce `|x|` for sin/cos. Caller must have already separated the
/// sign of `x`; this function operates on the absolute value.
///
/// Returns `(k mod 4, r, status)` such that
///
/// ```text
/// |x|  =  k · π/2 + r
/// |r| ≤ π/4 (with at most ~2 ULP overrun)
/// ```
///
/// `k` is `round(|x| · 2/π)` (round-half-away-from-zero — ties don't
/// arise in practice since the product is irrational).
///
/// `r` is returned at extended precision so the downstream Taylor
/// series in `sincos.rs` runs without losing the ~38 digits of
/// fractional residual that the windowed multiplication produced.
///
/// `x` must be finite. NaN, Infinity, and Zero are handled by the
/// caller before reaching here.
pub fn reduce<F: DecimalFormat>(x: F) -> (u32, Extended, Status) {
    let cls = x.classify();
    let (biased_exp, c) = match cls {
        Class::Finite {
            biased_exp,
            coefficient,
            ..
        } => (biased_exp, coefficient),
        // Caller filters these out, but be defensive.
        _ => return (0, Extended::from_format(x), Status::OK),
    };
    debug_assert!(c != 0);

    let q = biased_exp as i32 - F::BIAS; // unbiased exponent

    // Magnitude of |x|: |x| = c · 10^q. Decade ≈ q + digits(c) − 1.
    let dig_c = decimal_digit_count(c) as i32;
    let decade = q + dig_c - 1;

    // If |x| < π/4 ≈ 0.785, the reduction is trivially k = 0, r = |x|.
    // π/4 is between 10^{-1} and 1, so the safe shortcut is decade < -1
    // (i.e., |x| < 0.1 — well below π/4).
    if decade < -1 {
        // r = |x| as Extended.
        let mut r = Extended::from_format(x);
        r.sign = false;
        return (0, r, Status::INEXACT);
    }

    // Compute the window [i_lo, i_hi] of `2/π` digits we need.
    //
    // Mathematically i_lo = q − 1 (so the window's MSD is the digit
    // that lands at the 10^1 place of `c · 2/π`). Clipped to ≥ 1.
    // i_hi = q + I_HI_OFFSET. Clipped to ≤ TWO_OVER_PI_DIGITS — but
    // we sized the table so this never trips for a normal Decimal128.
    let i_hi_signed = q + I_HI_OFFSET as i32;
    if i_hi_signed < 1 {
        // Window empty: |x · 2/π| ≪ 10^{-FRAC_DIGITS}, so k = 0.
        let mut r = Extended::from_format(x);
        r.sign = false;
        return (0, r, Status::INEXACT);
    }
    let i_hi = (i_hi_signed as usize).min(table::TWO_OVER_PI_DIGITS);
    let i_lo_signed = q - 1;
    let i_lo = if i_lo_signed < 1 {
        1
    } else {
        i_lo_signed as usize
    };
    debug_assert!(i_lo <= i_hi);

    // W = window value as a U384 (≤ 78 decimal digits ≤ 2^259).
    let w = extract_window(i_lo, i_hi);

    // P = c × W. With FRAC_DIGITS = 76 the window is up to 115
    // digits and `c` is up to 34 digits — the product can reach
    // ~149 digits, exceeding `U384` (~115). The full product lives
    // in `U512` (~154 digits).
    let p = u384_mul_u128_to_u512(w, c);

    // The window value used the digits at positions i_lo..i_hi of 2/π,
    // which in `c · 10^q · 2/π` corresponds to the LSD of P sitting at
    // position 10^{q − i_hi} of x · 2/π. So P · 10^{q − i_hi} = the
    // windowed approximation to x · 2/π.
    //
    // We want round(x · 2/π) mod 4 and the fractional part. The
    // "decimal point" of P is positioned (i_hi − q) digits from the
    // right.
    //
    // For i_hi = q + I_HI_OFFSET (the unclipped case), this is exactly
    // I_HI_OFFSET = 113 (= FRAC_DIGITS + 33 + CARRY_GUARD = 76 + 33 + 4).
    // We rely on that: the table is sized so we never hit the i_hi clip
    // in practice (q_max + I_HI_OFFSET = 6111 + 113 = 6224 ≤ 6300, with
    // 76 digits of head-room before the table runs out). For the i_lo
    // clip (small q), shifting changes the window's interpretation:
    // dropping the digits below i_lo = 1 means we lose the d_0, d_{-1},
    // … positions, which don't exist because 2/π < 1. So the math works
    // out unchanged.
    debug_assert_eq!(
        i_hi - i_lo + 1,
        (i_hi_signed as usize - i_lo_signed.max(1) as usize) + 1
    );
    debug_assert!(i_hi as i32 - q == I_HI_OFFSET as i32);

    let split = split_product(p);

    // Decide whether the fractional part is ≥ 0.5: leading digit ≥ 5.
    let leading_frac = split.frac_digits[0];
    let round_up = leading_frac >= 5;

    let floor_mod_4 = split.floor_mod_100 % 4;
    let k_mod_4 = if round_up {
        (floor_mod_4 + 1) % 4
    } else {
        floor_mod_4
    };

    // Build r at extended precision. The caller passes the ABS value;
    // the residual sign is entirely determined by `round_up`.
    let r = make_residual(split.frac_digits, round_up, false);
    (k_mod_4, r, Status::INEXACT)
}

// ----------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    extern crate alloc;
    use super::*;

    #[test]
    fn first_digits_of_two_over_pi() {
        // 2/π = 0.63661977236758134307553505349005744813783858296183…
        let want = "63661977236758134307553505349005744813";
        for (i, ch) in want.char_indices() {
            let got = two_over_pi_digit(i + 1);
            let want_d = ch.to_digit(10).unwrap() as u8;
            assert_eq!(
                got,
                want_d,
                "digit {} mismatch: got {got}, want {want_d}",
                i + 1
            );
        }
    }

    #[test]
    fn pi_over_two_coef_matches_string() {
        // PI_OVER_TWO_COEF_38 must be the 38 leading decimal digits of
        // table::PI_OVER_TWO_STR (without the decimal point), parsed as
        // a u128.
        let s = table::PI_OVER_TWO_STR
            .chars()
            .filter(char::is_ascii_digit)
            .take(38)
            .collect::<alloc::string::String>();
        let derived: u128 = s.parse().unwrap();
        assert_eq!(derived, PI_OVER_TWO_COEF_38);
    }
}
