//! Extended-precision transcendental constants.
//!
//! Moved from `ferrodec/src/math/consts.rs` @ commit 82a7fe1
//! (P0a.2 c4). Only the format-agnostic half moves here: the nine
//! `*_EXT_STR` literals and their `*_ext()` [`Extended`] accessors,
//! plus the astro-float oracle that pins the literals. The
//! `Decimal128`-returning public `pi()` / `e()` / `ln2()` / `ln10()`
//! conveniences stay in the core crate (they are a Decimal128 API
//! surface, not a kernel internal).
//!
//! [`Extended`]: crate::extended::Extended

use crate::extended::Extended;
use crate::extended2::Extended2;

// Extended-precision constants — 55 decimal digits, comfortably above
// EXT_PRECISION = 50. Generated by `tools/gen_argred.py`'s mpmath
// helpers. Used by the faithfully-rounded transcendental kernels.
const PI_EXT_STR: &str = "3.141592653589793238462643383279502884197169399375105821";
const E_EXT_STR: &str = "2.718281828459045235360287471352662497757247093699959575";
const LN2_EXT_STR: &str = "0.6931471805599453094172321214581765680755001343602552541";
const LN10_EXT_STR: &str = "2.302585092994045684017991454684364207601101488628772976";
const INV_LN10_EXT_STR: &str = "0.4342944819032518276511289189166050822943970058036665661";
const INV_LN2_EXT_STR: &str = "1.442695040888963407359924681001892137426645954152985934";
// 1/π for the pi-scaled family's inverse kernels (ADR-0061).
const INV_PI_EXT_STR: &str = "0.3183098861837906715377675267450287240689192914809128974";
// π/4, π/2, and tan(π/8) at extended precision. Used by atan's
// argument reduction.
const PI_OVER_TWO_EXT_STR: &str = "1.570796326794896619231321691639751442098584699687552910";
const PI_OVER_FOUR_EXT_STR: &str = "0.7853981633974483096156608458198757210492923498437764552";
const TAN_PI_OVER_EIGHT_EXT_STR: &str = "0.4142135623730950488016887242096980785696718753769480732";

/// `π` at extended (≥ 50-digit) working precision.
#[must_use]
pub fn pi_ext() -> Extended {
    Extended::parse_str(PI_EXT_STR)
}

/// Euler's number `e` at extended precision.
#[must_use]
pub fn e_ext() -> Extended {
    Extended::parse_str(E_EXT_STR)
}

/// `ln(2)` at extended precision.
#[must_use]
pub fn ln2_ext() -> Extended {
    Extended::parse_str(LN2_EXT_STR)
}

/// `ln(10)` at extended precision.
#[must_use]
pub fn ln10_ext() -> Extended {
    Extended::parse_str(LN10_EXT_STR)
}

/// `1/ln(10)` at extended precision. Used in place of `Extended` /
/// `Extended` division when reducing `x = k · ln(10) + r` for `exp`.
#[must_use]
pub fn inv_ln10_ext() -> Extended {
    Extended::parse_str(INV_LN10_EXT_STR)
}

/// `1/ln(2)` at extended precision. Used by `log2(x) = ln(x) · 1/ln(2)`.
#[must_use]
pub fn inv_ln2_ext() -> Extended {
    Extended::parse_str(INV_LN2_EXT_STR)
}

/// `1/π` at extended precision. Used by the pi-scaled inverse family
/// (`asinPi = asin(x)/π` and siblings, ADR-0061).
#[must_use]
pub fn inv_pi_ext() -> Extended {
    Extended::parse_str(INV_PI_EXT_STR)
}

/// `π/2` at extended precision. Used by atan / asin / acos /
/// atan2 quadrant adjustments.
#[must_use]
pub fn pi_over_two_ext() -> Extended {
    Extended::parse_str(PI_OVER_TWO_EXT_STR)
}

/// `π/4` at extended precision.
#[must_use]
pub fn pi_over_four_ext() -> Extended {
    Extended::parse_str(PI_OVER_FOUR_EXT_STR)
}

/// `tan(π/8)` at extended precision — the threshold for atan's
/// inner argument reduction.
#[must_use]
pub fn tan_pi_over_eight_ext() -> Extended {
    Extended::parse_str(TAN_PI_OVER_EIGHT_EXT_STR)
}

// ----------------------------------------------------------------------------
// Rung 2 constants (ADR-0059, M5).
//
// The escalation ladder's 110-digit rung needs *wider* literals, not a
// widening of the 55-digit set: a re-parsed 55-digit literal would cap
// the rung's constant accuracy at rung 1 precision and silently defeat
// the escalation. 115 decimal digits, the same 5-guard-digit overshoot
// over `EXT2_PRECISION = 110` that the rung 1 set carries over 50.
// Generated by the same mpmath derivation as the 55-digit set
// (`tools/gen_argred.py`'s helpers; the generator's 55-digit rendering
// reproduces every `*_EXT_STR` literal above byte for byte, which is
// the generator self-check). Pinned independently against astro-float
// below (`extended2_constants_match_astro_float_to_110_digits`).

const PI_EXT2_STR: &str = "3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148086513282";
const E_EXT2_STR: &str = "2.718281828459045235360287471352662497757247093699959574966967627724076630353547594571382178525166427427466391932003";
const LN2_EXT2_STR: &str = "0.6931471805599453094172321214581765680755001343602552541206800094933936219696947156058633269964186875420014810205707";
const LN10_EXT2_STR: &str = "2.302585092994045684017991454684364207601101488628772976033327900967572609677352480235997205089598298341967784042286";
const INV_LN10_EXT2_STR: &str = "0.4342944819032518276511289189166050822943970058036665661144537831658646492088707747292249493384317483187061067447663";
const INV_LN2_EXT2_STR: &str = "1.442695040888963407359924681001892137426645954152985934135449406931109219181185079885526622893506344496997518309653";
const INV_PI_EXT2_STR: &str = "0.3183098861837906715377675267450287240689192914809128974953346881177935952684530701802276055325061719121456854535159";
const PI_OVER_TWO_EXT2_STR: &str = "1.570796326794896619231321691639751442098584699687552910487472296153908203143104499314017412671058533991074043256641";
const PI_OVER_FOUR_EXT2_STR: &str = "0.7853981633974483096156608458198757210492923498437764552437361480769541015715522496570087063355292669955370216283206";
const TAN_PI_OVER_EIGHT_EXT2_STR: &str = "0.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727350138462309123";

/// `π` at rung 2 (≥ 110-digit) working precision.
#[must_use]
pub(crate) fn pi_ext2() -> Extended2 {
    Extended2::parse_str(PI_EXT2_STR)
}

/// Euler's number `e` at rung 2 precision.
#[must_use]
pub(crate) fn e_ext2() -> Extended2 {
    Extended2::parse_str(E_EXT2_STR)
}

/// `ln(2)` at rung 2 precision.
#[must_use]
pub(crate) fn ln2_ext2() -> Extended2 {
    Extended2::parse_str(LN2_EXT2_STR)
}

/// `ln(10)` at rung 2 precision.
#[must_use]
pub(crate) fn ln10_ext2() -> Extended2 {
    Extended2::parse_str(LN10_EXT2_STR)
}

/// `1/ln(10)` at rung 2 precision.
#[must_use]
pub(crate) fn inv_ln10_ext2() -> Extended2 {
    Extended2::parse_str(INV_LN10_EXT2_STR)
}

/// `1/ln(2)` at rung 2 precision.
#[must_use]
pub(crate) fn inv_ln2_ext2() -> Extended2 {
    Extended2::parse_str(INV_LN2_EXT2_STR)
}

/// `1/π` at rung 2 width (ADR-0061).
#[must_use]
pub(crate) fn inv_pi_ext2() -> Extended2 {
    Extended2::parse_str(INV_PI_EXT2_STR)
}

/// `π/2` at rung 2 precision.
#[must_use]
pub(crate) fn pi_over_two_ext2() -> Extended2 {
    Extended2::parse_str(PI_OVER_TWO_EXT2_STR)
}

/// `π/4` at rung 2 precision.
#[must_use]
pub(crate) fn pi_over_four_ext2() -> Extended2 {
    Extended2::parse_str(PI_OVER_FOUR_EXT2_STR)
}

/// `tan(π/8)` at rung 2 precision.
#[must_use]
pub(crate) fn tan_pi_over_eight_ext2() -> Extended2 {
    Extended2::parse_str(TAN_PI_OVER_EIGHT_EXT2_STR)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extended::ExtNum;
    use crate::mock_format::MockFmt;

    /// Offline boundary-distance certification for the directly
    /// delivered π-family constants (ADR-0059 M8). The kernels hand
    /// `π/4`, `π/2`, `3π/4`, and `π` straight to the format rounder
    /// (atan(±∞), asin(±1), acos(0), acos(−1), atan2's axes and
    /// quadrants) without paying the runtime escalation predicate;
    /// this test is the once-and-for-all discharge that replaces it.
    ///
    /// The certificate has two legs, per format shape:
    ///
    /// 1. The delivered 55-digit rung 1 constant sits further than
    ///    `10^-46` (relative) from every grid point and midpoint of
    ///    the format (`!near_rounding_boundary` at a `10^4`-unit
    ///    budget, units of `10^-50`; the predicate's own 55→50-digit
    ///    normalization perturbs the measured distance by ≤ 1 unit).
    /// 2. The delivered rung 1 value agrees with the 115-digit rung 2
    ///    value to better than `10^-52` relative for the hand-curated
    ///    literals, and `10^-49` for the composed `3π/4` (its
    ///    `π/4 × 3` product rounds once at the 50-digit rung width —
    ///    in production exactly as here); the true constant is within
    ///    `10^-110` of the rung 2 value.
    ///
    /// Together: the delivered representation, the wide
    /// representation, and the true value all lie in one
    /// boundary-free interval of half-width `10^-46`, at least three
    /// orders wider than their mutual spread, so rounding the
    /// delivered value at the format width gives the true constant's
    /// correct rounding in every mode. Nothing here depends on the
    /// kernel error model.
    #[test]
    fn pi_family_constants_certified_against_format_boundaries() {
        fn certify<const P: u32, const B: i32>(label: &str) {
            // 10^4 units of 10^-50 ≡ a 10^-46 relative distance.
            let budget: u128 = 10_000;
            let pairs: [(&str, Extended, Extended2, i32); 4] = [
                ("pi/4", pi_over_four_ext(), pi_over_four_ext2(), -53),
                ("pi/2", pi_over_two_ext(), pi_over_two_ext2(), -53),
                (
                    "3pi/4",
                    pi_over_four_ext().mul(Extended::from_i32(3)),
                    pi_over_four_ext2().mul(Extended2::from_i32(3)),
                    -49,
                ),
                ("pi", pi_ext(), pi_ext2(), -53),
            ];
            for (name, c1, c2, agree_decade) in pairs {
                assert!(
                    !c2.near_rounding_boundary::<MockFmt<P, B>>(budget),
                    "{label}: {name} lies within 1e-45 of a format                      rounding boundary — constant delivery needs the                      runtime predicate after all"
                );
                // Leg 2: rung agreement, checked in decade arithmetic
                // (the difference's leading decade at least
                // `agree_decade` below the constant's).
                let d = Extended2::from_extended(c1).sub(c2).abs();
                if !d.is_zero() {
                    let decade_d = d.exponent() + d.digit_count() as i32 - 1;
                    let decade_c = c2.exponent() + c2.digit_count() as i32 - 1;
                    assert!(
                        decade_d - decade_c <= agree_decade,
                        "{label}: {name} rung disagreement at decade {}",
                        decade_d - decade_c
                    );
                }
            }
        }
        certify::<34, 6176>("Decimal128");
        certify::<16, 398>("Decimal64");
        certify::<7, 101>("Decimal32");
    }

    // ------------------------------------------------------------------
    // Extended-precision constants oracle
    //
    // The nine `*_EXT_STR` literals above were hand-curated via mpmath
    // (see `tools/gen_argred.py`). A single transposed digit in any of
    // them would silently degrade every transcendental kernel that
    // consumes it (most visibly `INV_LN10_EXT_STR` for `log10`,
    // `LN2_EXT_STR` for `log2`, `PI_OVER_TWO_EXT_STR` for atan's
    // argument reduction).
    //
    // The 2026-05-10 six-agent review (M1) flagged the absence of an
    // independent oracle for these literals: the only test was
    // `pi_is_about_three_point_one_four`, which checks π between 3.14
    // and 3.15 — wide enough to admit any digit-transposition past
    // the third decimal.
    //
    // Slice E.3 closes the gap by re-deriving each constant via
    // `astro-float` at 220-bit working precision (~66 decimal digits)
    // and asserting agreement to ≥ 50 digits. The 50-digit envelope
    // matches `EXT_PRECISION`; a literal that drifts past 50 digits
    // would no longer round correctly through `Extended::parse_str`
    // and the assertion fires immediately.

    use astro_float::{BigFloat, Consts, RoundingMode as AfRm};

    /// Working precision for the astro-float reference computations.
    /// 220 bits ≈ 66 decimal digits — well above the 50-digit
    /// agreement target so the comparison's last bits are clean.
    const ORACLE_P: usize = 220;

    fn parse_bf(s: &str, cc: &mut Consts) -> BigFloat {
        BigFloat::parse(s, astro_float::Radix::Dec, ORACLE_P, AfRm::None, cc)
    }

    /// Assert `|our - reference| < 10^{-50}`. The bound is chosen so
    /// the agreement covers the full `EXT_PRECISION = 50` working
    /// envelope; a constant that drifts past that bound is no longer
    /// a faithful 50-digit literal.
    fn assert_ext_str_matches(label: &str, our_str: &str, reference: &BigFloat, cc: &mut Consts) {
        let ours = parse_bf(our_str, cc);
        let diff = ours.sub(reference, ORACLE_P, AfRm::None).abs();
        let tolerance = parse_bf("1e-50", cc);
        assert!(
            matches!(
                diff.partial_cmp(&tolerance),
                Some(core::cmp::Ordering::Less)
            ),
            "{label}: {our_str} differs from astro-float reference by ≥ 10⁻⁵⁰"
        );
    }

    #[test]
    fn extended_constants_match_astro_float_to_50_digits() {
        let mut cc = Consts::new().expect("init consts");

        // π
        let pi_ref = cc.pi(ORACLE_P, AfRm::None);
        assert_ext_str_matches("PI_EXT_STR", PI_EXT_STR, &pi_ref, &mut cc);

        // e = exp(1)
        let one = parse_bf("1", &mut cc);
        let e_ref = one.exp(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("E_EXT_STR", E_EXT_STR, &e_ref, &mut cc);

        // ln(2)
        let two = parse_bf("2", &mut cc);
        let ln2_ref = two.ln(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("LN2_EXT_STR", LN2_EXT_STR, &ln2_ref, &mut cc);

        // ln(10)
        let ten = parse_bf("10", &mut cc);
        let ln10_ref = ten.ln(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches("LN10_EXT_STR", LN10_EXT_STR, &ln10_ref, &mut cc);

        // 1 / ln(10)
        let inv_ln10_ref = ln10_ref.reciprocal(ORACLE_P, AfRm::None);
        assert_ext_str_matches("INV_LN10_EXT_STR", INV_LN10_EXT_STR, &inv_ln10_ref, &mut cc);

        // 1 / ln(2)
        let inv_ln2_ref = ln2_ref.reciprocal(ORACLE_P, AfRm::None);
        assert_ext_str_matches("INV_LN2_EXT_STR", INV_LN2_EXT_STR, &inv_ln2_ref, &mut cc);

        let inv_pi_ref = pi_ref.reciprocal(ORACLE_P, AfRm::None);
        assert_ext_str_matches("INV_PI_EXT_STR", INV_PI_EXT_STR, &inv_pi_ref, &mut cc);

        // π / 2
        let pi_over_two_ref = pi_ref.div(&two, ORACLE_P, AfRm::None);
        assert_ext_str_matches(
            "PI_OVER_TWO_EXT_STR",
            PI_OVER_TWO_EXT_STR,
            &pi_over_two_ref,
            &mut cc,
        );

        // π / 4
        let four = parse_bf("4", &mut cc);
        let pi_over_four_ref = pi_ref.div(&four, ORACLE_P, AfRm::None);
        assert_ext_str_matches(
            "PI_OVER_FOUR_EXT_STR",
            PI_OVER_FOUR_EXT_STR,
            &pi_over_four_ref,
            &mut cc,
        );

        // tan(π / 8)
        let eight = parse_bf("8", &mut cc);
        let pi_over_eight = pi_ref.div(&eight, ORACLE_P, AfRm::None);
        let tan_pi_eight_ref = pi_over_eight.tan(ORACLE_P, AfRm::None, &mut cc);
        assert_ext_str_matches(
            "TAN_PI_OVER_EIGHT_EXT_STR",
            TAN_PI_OVER_EIGHT_EXT_STR,
            &tan_pi_eight_ref,
            &mut cc,
        );
    }

    // ------------------------------------------------------------------
    // Rung 2 constants oracle (ADR-0059, M5). Same discipline at the
    // wider width: re-derive each 115-digit literal via astro-float at
    // 420-bit working precision (~126 decimal digits) and assert
    // agreement to < 10^-110, the full `EXT2_PRECISION` envelope.

    /// Working precision for the rung 2 reference computations.
    const ORACLE_P2: usize = 420;

    fn parse_bf2(s: &str, cc: &mut Consts) -> BigFloat {
        BigFloat::parse(s, astro_float::Radix::Dec, ORACLE_P2, AfRm::None, cc)
    }

    fn assert_ext2_str_matches(label: &str, our_str: &str, reference: &BigFloat, cc: &mut Consts) {
        let ours = parse_bf2(our_str, cc);
        let diff = ours.sub(reference, ORACLE_P2, AfRm::None).abs();
        let tolerance = parse_bf2("1e-110", cc);
        assert!(
            matches!(
                diff.partial_cmp(&tolerance),
                Some(core::cmp::Ordering::Less)
            ),
            "{label}: {our_str} differs from astro-float reference by ≥ 10⁻¹¹⁰"
        );
    }

    #[test]
    fn extended2_constants_match_astro_float_to_110_digits() {
        let mut cc = Consts::new().expect("init consts");

        let pi_ref = cc.pi(ORACLE_P2, AfRm::None);
        assert_ext2_str_matches("PI_EXT2_STR", PI_EXT2_STR, &pi_ref, &mut cc);

        let one = parse_bf2("1", &mut cc);
        let e_ref = one.exp(ORACLE_P2, AfRm::None, &mut cc);
        assert_ext2_str_matches("E_EXT2_STR", E_EXT2_STR, &e_ref, &mut cc);

        let two = parse_bf2("2", &mut cc);
        let ln2_ref = two.ln(ORACLE_P2, AfRm::None, &mut cc);
        assert_ext2_str_matches("LN2_EXT2_STR", LN2_EXT2_STR, &ln2_ref, &mut cc);

        let ten = parse_bf2("10", &mut cc);
        let ln10_ref = ten.ln(ORACLE_P2, AfRm::None, &mut cc);
        assert_ext2_str_matches("LN10_EXT2_STR", LN10_EXT2_STR, &ln10_ref, &mut cc);

        let inv_ln10_ref = ln10_ref.reciprocal(ORACLE_P2, AfRm::None);
        assert_ext2_str_matches(
            "INV_LN10_EXT2_STR",
            INV_LN10_EXT2_STR,
            &inv_ln10_ref,
            &mut cc,
        );

        let inv_ln2_ref = ln2_ref.reciprocal(ORACLE_P2, AfRm::None);
        assert_ext2_str_matches("INV_LN2_EXT2_STR", INV_LN2_EXT2_STR, &inv_ln2_ref, &mut cc);

        let inv_pi_ref = pi_ref.reciprocal(ORACLE_P2, AfRm::None);
        assert_ext2_str_matches("INV_PI_EXT2_STR", INV_PI_EXT2_STR, &inv_pi_ref, &mut cc);

        let pi_over_two_ref = pi_ref.div(&two, ORACLE_P2, AfRm::None);
        assert_ext2_str_matches(
            "PI_OVER_TWO_EXT2_STR",
            PI_OVER_TWO_EXT2_STR,
            &pi_over_two_ref,
            &mut cc,
        );

        let four = parse_bf2("4", &mut cc);
        let pi_over_four_ref = pi_ref.div(&four, ORACLE_P2, AfRm::None);
        assert_ext2_str_matches(
            "PI_OVER_FOUR_EXT2_STR",
            PI_OVER_FOUR_EXT2_STR,
            &pi_over_four_ref,
            &mut cc,
        );

        let eight = parse_bf2("8", &mut cc);
        let pi_over_eight = pi_ref.div(&eight, ORACLE_P2, AfRm::None);
        let tan_pi_eight_ref = pi_over_eight.tan(ORACLE_P2, AfRm::None, &mut cc);
        assert_ext2_str_matches(
            "TAN_PI_OVER_EIGHT_EXT2_STR",
            TAN_PI_OVER_EIGHT_EXT2_STR,
            &tan_pi_eight_ref,
            &mut cc,
        );
    }

    /// Each rung 2 accessor parses its literal into a coefficient at
    /// most `EXT2_PRECISION + 5` digits (the invariant `parse_str`
    /// debug-asserts) and agrees in value with its rung 1 counterpart
    /// to rung 1 width — the two sets describe the same constants.
    #[test]
    fn extended2_constants_are_consistent_with_rung1() {
        let pairs = [
            (super::pi_ext(), super::pi_ext2()),
            (super::e_ext(), super::e_ext2()),
            (super::ln2_ext(), super::ln2_ext2()),
            (super::ln10_ext(), super::ln10_ext2()),
            (super::inv_ln10_ext(), super::inv_ln10_ext2()),
            (super::inv_ln2_ext(), super::inv_ln2_ext2()),
            (super::pi_over_two_ext(), super::pi_over_two_ext2()),
            (super::pi_over_four_ext(), super::pi_over_four_ext2()),
            (
                super::tan_pi_over_eight_ext(),
                super::tan_pi_over_eight_ext2(),
            ),
        ];
        for (narrow, wide) in pairs {
            // |wide − widen(narrow)| relative to the value is below
            // 10^-54 (the 55-digit literal's own resolution).
            let widened = Extended2::from_extended(narrow);
            let d = wide.sub(widened);
            if d.is_zero() {
                continue;
            }
            let d_adj = d.exp + d.coef.decimal_digit_count() as i32 - 1;
            let w_adj = wide.exp + wide.coef.decimal_digit_count() as i32 - 1;
            assert!(
                d_adj <= w_adj - 54,
                "rung1/rung2 constant disagreement above 10^-54 relative"
            );
        }
    }
}
